### ISSUE TITLE
how to copy and paste events in ctrl + C and ctrl + v

### ISSUE THREAD

**Issue by BensonLam** [xtermjs/xterm.js#4745] opened 2023-09-03 14:49 UTC
pls give me an idea, i want to copy and paste whether it is a keyboard Evt or mouse evt

**Comment by Tyriar** [comment] 2023-09-11 13:59
duplicate of https://github.com/xtermjs/xterm.js/issues/2478

**Closed by Tyriar** 2023-09-11 13:59 UTC
