### ISSUE TITLE
Highlight search results with animation

### ISSUE THREAD

**Issue by levani** [xtermjs/xterm.js#3563] opened 2021-11-23 09:29 UTC
I think it would be a nice addition to add better highlight animation when search result is found. With current highlight it a bit difficult to spot where the search result is located exactly.

Here is an example from macos termiinal:

https://user-images.githubusercontent.com/184472/142999863-16d8f39e-42f7-4aa5-a641-27d942f64666.mov

**Comment by Tyriar** [comment] 2021-11-23 14:14
duplicate of https://github.com/xtermjs/xterm.js/issues/1653

**Closed by Tyriar** 2021-11-23 14:14 UTC
