### ISSUE TITLE
Login prefix is appended again after windows is resized

### ISSUE THREAD

**Issue by kishanvk** [xtermjs/xterm.js#1807] opened 2018-12-03 08:14 UTC
## Details
- Browser and browser version: Chrome 63.0.3239.84
- OS version: 
- xterm.js version: ^3.8.0

### Steps to reproduce

1. run any command
2. resize the window
3. press up arrow to rerun the previous command

It appends the login prefix something like below:
"CLI (user@host) > CLI (user@host) > cli-command"
In the above output "CLI (user@host) >" is repeated.

**Comment by jerch** [comment] 2018-12-03 11:23
@kishanvk Please provide a more detailed problem description and some screenshots showing the issue. Also "resizing the window" seems odd to me since we dont provide such a feature out of the box (its left to integrators).

**Comment by kishanvk** [comment] 2018-12-03 11:46
Hi Jerch,

Let me explain:

Yes i agree that window resize is not related. 

My application is similar to WebSSH2 "https://github.com/billchurch/WebSSH2", where upon window resize event we are calling term.fit() and send the the term.cols and term.rows in websocket message to server. Server will accordingly set the cols and rows to the ssh server.

I occurs only if i resize the window and press up/down arrow keys to run previous commands.

Let me know if you need any further details.

**Comment by skprabhanjan** [comment] 2018-12-03 15:36
@kishanvk , CC: @jerch 
I tried following the steps in order to reproduce this but I don't seem to get this issue on any sort of resize( Chrome window and terminal resize by changing rows and cols manually)

**Comment by jerch** [comment] 2018-12-03 16:47
@skprabhanjan Thx for testing it, same for me - I cannot repro it with FF or Chrome by manually resizing in the demo with a local shell. Also starting ssh within this shell and logging into a remote machine works without problems.

@kishanvk Is the new size correctly applied after resizing, so there is no early wrapping with a big black area at right border and such? Could you enable the debug mode and post the escape sequences that show up in the logs? (Watch out - if you directly input the password at ssh prompt in the terminal those chars will be in the logs too, dont post this part).
How do you spawn ssh (as command to node-pty or within a shell?), any special env settings? Does this also happen with a normal local shell or just with ssh? Do you have any advanced shell setup scripts running (like oh-my-zsh)?
Maybe one of those questions will lead to the culprit.

**Closed** 2019-10-07 18:01 UTC
Labels: needs more info
