### ISSUE TITLE
Problem with emojis/unicode (assumed double-width?)

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1059] opened 2017-10-12 16:35 UTC
In current v3, Emojis seem to take up two cells. Using the arrow keys, two cells are jumped instead of one. Deleting also clears two cells.

![kapture 2017-10-12 at 18 34 05](https://user-images.githubusercontent.com/2785983/31507753-17d2de54-af7c-11e7-8def-bc919164639b.gif)

**Comment by Tyriar** [comment] 2017-10-13 20:43
I can't reproduce this on macOS/bash. I wouldn't expect it to happen unless we tried to tweak with the emoji width (make it non-1). Any more details on repro steps would be useful.

**Comment by mofux** [comment] 2017-10-13 20:56
Reproduce (OSX, MacOS High Sierra)
- start v3 demo
- paste 😀 multiple times
- hit left arrow key multiple times, see how it jumps two cells each time and runs into the cell boundaries.

Are you already on MacOS High Sierra, because I am? Maybe it is also related to node-pty - I can see that when inserting an emoji in `Terminal.app` it automatically adds a space after the emoji, and even more, I cannot select that space, it's like High Sierra would threat it as a double-width character...

Terminal.app on MacOS High Sierra
![kapture 2017-10-13 at 22 55 32](https://user-images.githubusercontent.com/2785983/31566159-aba1b27a-b069-11e7-871a-5d6beaa5f007.gif)

**Comment by Tyriar** [comment] 2017-10-15 06:56
This might be a high sierra thing where they tried to make Emojis better in the terminal? I can't update currently as it messes up rendering in Electron apps.

**Comment by mofux** [comment] 2017-10-19 16:57
I hate to say that I've upgraded and now I'm stuck with tons of rendering glitches in all those chromium based apps 😤

**Comment by Tyriar** [comment] 2017-10-21 00:23
Yeah I was careful to track feedback before updating as similar things happened with Sierra I think.

**Comment by Tyriar** [comment] 2018-02-21 18:51
I notice that Terminal.app has a nice emoji experience where they're treated as proper wide characters, we can probably do it if they can 😄

**Comment by mandel59** [comment] 2018-04-13 16:12
[UAX #11 East Asian Width, Revision 31](https://www.unicode.org/reports/tr11/tr11-31.html) changed emoji _East Asian Wide_ (double-width), and `wcswidth` in wchar.h returns the width of strings. I guess macOS High Sierra would have supported the update.
xterm.js's `wcwidth` in `src/CharWidth.ts` doesn't have supported it yet.

**Comment by Tyriar** [comment] 2018-04-13 17:24
@mandel59 thanks for the info!

**Comment by Tyriar** [comment] 2018-04-13 17:29
@mandel59 I think this issue is specific to emoji, I think CJK chars should be correctly categorized as double width chars (some components may be broken though like https://github.com/xtermjs/xterm.js/issues/1387)

**Comment by tonycoco** [comment] 2018-07-24 18:24
Reference: https://github.com/gnachman/iTerm2/blob/master/sources/NSCharacterSet+iTerm.m has some mapping solutions too.

**Comment by Tyriar** [comment] 2018-09-22 18:15
VS Code issue: https://github.com/Microsoft/vscode/issues/59145

Apparently flutter run demonstrates this behavior

**Comment by DanTup** [comment] 2018-09-24 11:04
Here's a small Dart repro for what we're seeing that doesn't require Flutter (does require Dart though):

```
import 'dart:async';

import 'dart:io';

// Windows console font has a limited set of Unicode characters.
final _animation = Platform.isWindows
    ? <String>[r'-', r'\', r'|', r'/']
    : <String>['🌕', '🌖', '🌗', '🌘', '🌑', '🌒', '🌓', '🌔'];
final _backspace = '\b' * _animation[0].length;

main() {
  int ticks = 0;
  void update(Timer timer) {
    if (ticks % 50 == 0) {
      stdout.write('\nDoing thing... ');
    }
    stdout.write('$_backspace${_animation[ticks++ % _animation.length]}');
  }

  new Timer.periodic(const Duration(milliseconds: 100), update);
}
```

Save as a `.dart` file and then run it with `dart xxx.dart`. This code here issues two backspaces for this character, which in a standard macOS terminal correctly removes the character. However, in the VS Code terminal it will backspace the emoji and then another character. If the emoji was at the start of the line this does nothing, but if it's not, the rendering slowly creeps to the left by a character (and leaves the right-half of the icon after it).

If I you remove the `* _animation[0].length` from the backspace so that it always does a single backspace, it works fine in the VS Code terminal, but no longer backspaces enough in the macOS Terminal (so the moons then creep to the right!).

**Comment by juliusecker** [comment] 2019-02-21 16:13
VSCode 1.31.1 on Ubuntu 18.04 experiences this issue. I just want emojis in my console damn it! 

Also when you scroll up or down your command history with the arrow keys, artifacts are picked up such that when you get to a command you want to run, chances are its illegible. 

Steps:

Added an emoji to my prompt:
![screenshot from 2019-02-21 11-10-15](https://user-images.githubusercontent.com/28567778/53183489-6f173000-35c9-11e9-8e99-d46ce0d7d94d.png)
Hit up arrow once to get to command `npm i`
![screenshot from 2019-02-21 11-10-55](https://user-images.githubusercontent.com/28567778/53183490-6f173000-35c9-11e9-8823-255e757bc599.png)

Notice the rogue `n` that was added to the prompt.

Remove the emoji from the terminal in `.bashrc` and reload the term and the bug goes away.

**Comment by desko27** [comment] 2019-02-22 15:28
First things first, I wanted to thank you guys for your amazing work.

VSCode 1.31.1 on macOS Mojave 10.14.3 experiences the same. The `n` thing mentioned by @juliusecker happens to me too, exactly as he described.

**Comment by keyone** [comment] 2019-05-09 04:28
I have the same bug as mentioned by @juliusecker. 
VSCode Version 1.33.1 (1.33.1) 51b0b28134d51361cf996d2f0a1c698247aeabd8 2019-04-11T08:14:39.158Z
System Version: macOS 10.14.4 (18E226)
zsh 5.7.1 (x86_64-apple-darwin17.7.0)

**Comment by JustinGrote** [comment] 2019-08-13 21:53
Very simple to reproduce in VSCode and Powershell.
```powershell
"Emoji Normal"
"😊1😊2😊3😊4"
"Emoji with Padding Spaces - What it should look like"
"😊  1😊  2😊  3😊  4"
```
![image](https://user-images.githubusercontent.com/15258962/62979937-053e4d00-bdda-11e9-9070-978b11440d1a.png)

Are there any resources assigned to this item? Looks like lots of regressions in other programs (Hyper, etc.) as seen on this issue thread.

**Comment by Tyriar** [comment] 2019-08-16 14:19
@jerch is this a duplicate of https://github.com/xtermjs/xterm.js/issues/1709?

**Comment by jerch** [comment] 2019-08-16 14:40
@Tyriar Yes kinda, its just an example where ppl are most likely will face it - emojis :smile_cat:

**Comment by Tyriar** [comment] 2019-08-16 16:50
I guess we'll keep them both opened as this describes the problem well and #1709 looks more at the solution.

**Comment by benc-uk** [comment] 2019-10-06 12:54
Issue has been around nearly two years, any update?

**Comment by Tyriar** [comment] 2019-10-07 13:50
@jerch wants to get to it soon, he has a bunch of stuff ongoing atm though. One of the big blockers for this was the new addon system which is now released.

**Closed** 2019-10-07 17:56 UTC
Labels: area/renderer, type/bug
