### ISSUE TITLE
ZWSP unexpectedly taking up a space

### ISSUE THREAD

**Issue by adamyi** [xtermjs/xterm.js#5237] opened 2024-12-09 07:23 UTC
I found that if a line starts with a ZWSP (zero-width space), or there's a ZWSP immediately following a CSI sequence, it takes up a cell, whereas it does not on other terminals (I tested urxvt, uxterm, kitty, gnome-terminal, terminator, qterminal and xfce4-terminal).

I believe when apps print zero-width space, they do not intend for it to be visible.

This is what it looks like on xterm.js:
![xterm js](https://github.com/user-attachments/assets/2b047c91-8a67-4f51-9728-ca69f89acbe1)

This is what it looks like on kitty:
![kitty](https://github.com/user-attachments/assets/1459f547-a468-41f5-af42-78e60dc3fdf2)

**Comment by Tyriar** [comment] 2024-12-12 14:17
duplicate of https://github.com/xtermjs/xterm.js/issues/2668

**Closed by Tyriar** 2024-12-12 14:17 UTC

**Comment by adamyi** [comment] 2024-12-18 08:30
Thanks!
