### ISSUE TITLE
SearchAddon shows wrong selection when bounding with wide unicode chars

### ISSUE THREAD

**Issue by gera2ld** [xtermjs/xterm.js#3235] opened 2021-01-29 04:02 UTC
When the matched content starts right after a wide unicode char, the selection appears to start from the middle of the unicode char before it.

<img width="249" alt="Screen Shot 2021-01-29 at 11 51 20" src="https://user-images.githubusercontent.com/3139113/106229384-6bb26780-6228-11eb-832a-ac1c1826675a.png">

When the matched content ends with a wide unicode char, the selection appears to include only half of the char.

<img width="304" alt="Screen Shot 2021-01-29 at 12 01 30" src="https://user-images.githubusercontent.com/3139113/106230113-c00a1700-6229-11eb-90c8-6c4208f0ab28.png">

This can be reproduced in browsers and VSCode.

## Details
- Browser and browser version: Firefox 85 / Chrome 88 / VSCode 1.52.1
- OS version: macOS 10.15.7
- xterm.js version: 4.9.0

### Steps to reproduce

1. Input `中文xxx` in terminal
2. Search `xxx` for the first case
3. Search `中` for the second case

**Comment by Tyriar** [comment] 2021-01-29 15:20
duplicate of https://github.com/xtermjs/xterm.js/issues/1686

**Closed by Tyriar** 2021-01-29 15:20 UTC
