### ISSUE TITLE
blink text problem

### ISSUE THREAD

**Issue by ppacory** [xtermjs/xterm.js#2891] opened 2020-04-30 14:16 UTC
this code print in term doesn't blink :

`text = "\u001b[5mTitle of the Program\u001b[0m"` or
`text = "\x1B[5mTitle of the Program\x1B[0m"`   

the other ansi code like inverted,bold,underline work perfectly ...
Any idea ?

**Comment by Tyriar** [comment] 2020-04-30 16:09
duplicate of https://github.com/xtermjs/xterm.js/issues/944

**Closed by Tyriar** 2020-04-30 16:09 UTC
