### ISSUE TITLE
Can't input text in Safari 15 with InputMethodKit such as 搜狗拼音输入法

### ISSUE THREAD

**Issue by Innei** [xtermjs/xterm.js#3639] opened 2022-02-14 06:38 UTC
Can't input text in Safari 15 with speical input source such as 搜狗拼音输入法 English mode.

## Details
- Browser and browser version: Safari 15.2
- OS version: macOS 12.2.1
- xterm.js version: 4.17.0

### Steps to reproduce

1. Go codesandbox https://codesandbox.io/s/intelligent-smoke-eovbu?file=/index.html
2. Open with Safari
3. Use [搜狗拼音输入法](https://pinyin.sogou.com/mac/)'s English mode to input text.

**It look like this issue: https://github.com/xtermjs/xterm.js/issues/3396**

**Comment by Innei** [comment] 2022-02-14 06:40
https://user-images.githubusercontent.com/41265413/153812876-2065a3b2-1041-4bb9-9d3a-645fbd37c65d.mov

**Comment by Innei** [comment] 2022-02-14 06:41
Chrome is work expected.

**Comment by childrentime** [comment] 2022-02-27 06:31
@Innei  It might be because of xterm's css style issue. 
```css
.xterm {
    position: relative;
    user-select: none;
    -ms-user-select: none;
    -webkit-user-select: none;
}
```
You can get reference from here. 
https://github.com/facebook/react/issues/16836

**Comment by Innei** [comment] 2022-03-16 15:01
@childrentime Not working, becuase xterm has not input, maybe use some hack to simulate an input box.

I add `user-select: none;` to xterm element, not working, then I set `.xterm * {user-select: none;}`, it can input ascii char in speical mode, but can not input Chinese.

**Comment by ShikiSuen** [comment] 2022-03-16 15:16
Please amend the title of this issue ticket.
"speical input source" -> "InputMethodKit".
Multiple Chinese input methods have the same issue.

**Comment by ShikiSuen** [comment] 2022-03-17 10:46
Further tests confirmed that this issue is IME-specific.
vChewing IME will fix this issue in the incoming 1.3.9b release.

**Comment by Tyriar** [comment] 2022-03-28 19:54
Closing as it's an IME issue, thanks for the investigation

**Closed by Tyriar** 2022-03-28 19:54 UTC

**Comment by ShikiSuen** [comment] 2022-03-29 02:40
@Tyriar I think I need to update my comment:

Although this issue can be avoidable by doing something on the IME developers' side, it can still be considered as having lack of compatibility between xtermjs and the InputMethodKit since xtermjs rejects those inputs which other usual apps don't reject.

Thankfully, this issue is bypassable by simply enabling "Use CapsLock to switch between alphanumeric keyboard layout and an input method" in macOS (probably starting with macOS releases shipped by the first-generation Thunderbolt 3 models of MacBook Pro).

**Comment by Tyriar** [comment] 2022-03-29 12:21
@ShikiSuen this sort of problem has come up before and if we try to workaround it to play nicely with the IME it often ends up regressing other IMEs. If it can be fixed on the IME side so it acts more proper then we can avoid the risk of regressions in other areas.
