### ISSUE TITLE
Selection doesn't work when container is moved with transform translate

### ISSUE THREAD

**Issue by ofirrifo** [xtermjs/xterm.js#1810] opened 2018-12-04 13:30 UTC
## Details
- Browser and browser version: chrome 70.0.3538.110
- OS version: macOs Mojave 10.14.1
- xterm.js version: "^3.8.0"

### Steps to reproduce
I need to give away to a user to copy from the terminal by mark some text.
it works just fine  but once I use the css style: transform: translate(500px, 500px)
the select text was not working properly.
I have a parent div that wraps the terminal div container on the parent div I set this style.

once I remove this style it back to work but then I need to found another way to position the dialog
which is the parent div

[jsfiddle example for my issue](https://jsfiddle.net/zger2wtx/77/)
BTW thanks for this great terminal :)

**Comment by Tyriar** [comment] 2018-12-04 17:17
Related: https://github.com/xtermjs/xterm.js/issues/1684

**Comment by zxlin** [comment] 2019-01-25 04:51
I'm also getting this behavior, essentially I implement xterm.js inside a draggable pane (using https://github.com/mzabriskie/react-draggable) and the draggable pane moves itself using 
`transform: translate(x, y);`
I think I saw in another post that `transform` is the trouble maker here, so sure enough, temporarily removing the `transform` style on the parent container of xterm reinstates the expected context menu behavior. However, I'd still want to have the pane be draggable, so I can't simply remove the CSS rule. 

My best guess right now is that the `.xterm-helper-textarea` element is the issue, it looks like the `top` and `left` style is set incorrectly due to the parent container's `translate` style. Just want to confirm that with you @Tyriar and see if there's any way to fix this or workaround it?

**Comment by Tyriar** [comment] 2019-01-25 16:35
@zxlin are you on v3.10? This might already be working (see https://github.com/xtermjs/xterm.js/issues/1684)

**Comment by zxlin** [comment] 2019-01-25 18:05
@Tyriar Yup, I'm on v3.10.1 and the problem still exists. 

I think the problem is that clientX & clientY is wrong when the parent container has a `transform` style.

**Comment by Tyriar** [comment] 2019-01-26 04:35
@zxlin I think something else must be going on for you, if you're talking about the textarea being in the wrong position then that is probably a different issue. I just tested the original jsfiddle and updated it to use 3.10.1 (was 2.9.2) and it works fine now so I'm closing this off. Feel free to create a new bug, a jsfiddle would be very helpful for whoever picks it up 👍

**Closed by Tyriar** 2019-01-26 04:35 UTC
Labels: area/mouse-support, help wanted, needs more info, type/bug
