### ISSUE TITLE
Japanese 2 byte width space('　') is not handled properly on Edge.

### ISSUE THREAD

**Issue by zfanta** [xtermjs/xterm.js#1548] opened 2018-07-05 10:20 UTC
When I type Japanese 2 byte width space('　') on Edge, `_handleAnyTextareaChanges` called and composition events are triggered. then Japanese 2 byte width space('　') is put 2 times.

![xterm js 2018-07-05 18-56-03](https://user-images.githubusercontent.com/6619332/42317700-ee442984-8087-11e8-91dc-d4815648e901.gif)

## Details
- Browser and browser version: IE11, Edge
- OS version: Windows 10
- xterm.js version: 3.3.0, 3.4.1

### Steps to reproduce

1. Switch to Japanese keyboard(Hiragana).
2. Type Japanese 2 byte width space('　').

**Comment by Tyriar** [comment] 2018-07-05 14:51
Looks like a duplicate of https://github.com/xtermjs/xterm.js/issues/1527

**Closed by Tyriar** 2018-07-05 14:51 UTC
