### ISSUE TITLE
Column selection isn't working correctly

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3855] opened 2022-06-11 13:09 UTC
Repro: Alt+click and drag in the terminal

- Moving right on the same line does not make a selection
- Moving to top-right or bottom-left doesn't make a selection (this works in canvas renderer only?)
- Cursor isn't correct

![Recording 2022-06-11 at 06 04 10](https://user-images.githubusercontent.com/2193314/173189313-d9256131-01da-4cbd-8ff4-ee32bc0d50a5.gif)

Correct behavior in VS Code 1.67.0:

![Recording 2022-06-11 at 06 07 07](https://user-images.githubusercontent.com/2193314/173189330-132000a9-139c-4d2d-ab45-c2652a83dbb2.gif)

**Comment by Tyriar** [comment] 2022-06-11 13:16
Should be able to write an api test for this

**Comment by silamon** [comment] 2022-06-11 15:23
The "moving to top-right or bottom-left doesn't make a selection" isn't a regression but something that's been in like forever. 
For DOM: Seems like the width of the selection element gets negative. Swapping colStart with colEnd in those cases will fix it. 
https://github.com/xtermjs/xterm.js/blob/48b8e31794ff218bc724202b037eb0a81de38ca8/src/browser/renderer/dom/DomRenderer.ts#L334-L341 
I couldn't reproduce the other mentioned things in xterm demo, but it definitely exists in vscode. (Notice how alt activates the menu shortcuts in the window bar.)

**Comment by Tyriar** [comment] 2022-06-11 23:24
> The "moving to top-right or bottom-left doesn't make a selection" isn't a regression but something that's been in like forever.

@silamon the gif shows it was working before?

> I couldn't reproduce the other mentioned things in xterm demo, but it definitely exists in vscode

Not sure about the corner thing but if it's only in VS Code then chances are it's related to padding around the terminal elements.

**Comment by silamon** [comment] 2022-06-12 06:44
I see that the code has changed for WebGL renderer, so you could be correct that it was working for WebGL before. 
https://github.com/xtermjs/xterm.js/blob/48b8e31794ff218bc724202b037eb0a81de38ca8/addons/xterm-addon-webgl/src/WebglRenderer.ts#L458-L459
It could be the same thing that I mentioned for DOM renderer now. startCol is higher than endCol for top-right and bottom-left and this only happens in columnSelectMode.

**Closed** 2022-06-14 16:40 UTC
Labels: type/bug, area/selection
