### ISSUE TITLE
xterm-addon-fit  Shrinking the screen doesn't work

### ISSUE THREAD

**Issue by xiaolannuoyi** [xtermjs/xterm.js#3564] opened 2021-11-24 10:17 UTC
## Details
- Browser and browser version: chrome/版本 96.0.4664.55（正式版本） (arm64)
- OS version: macos 12.0.1 (21A559)
- xterm.js version: 4.0.5
- xterm-addon-fit: 0.5.0
### Steps to reproduce

1. xterm-addon-fit 扩大屏幕时好使，缩小屏幕时不好使
```
initTerm() {
      const term = new Terminal(this.option)
      this.fitAddon = new FitAddon()
      term.loadAddon(this.fitAddon)
      term.open(this.$refs.terminal)
      term.write(this.initText)
      this.fitAddon.fit()

      return term
    },
 onResize: debounce(function () {
      console.warn('resize')
      this.fitAddon.fit()
    }, 0),
    onTerminalResize() {
      window.addEventListener('resize', this.onResize)
      this.term.onResize(this.resizeRemoteTerminal)
    },
    removeResizeListener() {
      window.removeEventListener('resize', this.onResize)
    },
```

![aaa](https://user-images.githubusercontent.com/21079721/143219345-c4b696c5-db76-4f0b-9a6a-2544ff45243b.gif)

**Comment by xiaolannuoyi** [comment] 2021-11-25 02:57
如果初始化的时候就使用fit，那么屏幕缩小不能小于初始的col，否则就不起作用。
若初始不使用fit，那么屏幕缩小时，col<103时就不起作用了

**Comment by xiaolannuoyi** [comment] 2021-11-26 02:46
我发现当缩小不好使 是因为`xterm-viewport`这个样式
![image](https://user-images.githubusercontent.com/21079721/143518997-d8fa6280-1ee2-4448-a3d6-daa68475f444.png)

**Comment by xiaolannuoyi** [comment] 2021-11-26 09:23
目前的解决办法就是 初始化的时候 不使用fit ，并将col设置小点

**Comment by Tyriar** [comment] 2021-11-29 15:39
This looks like an issue on your end, the element's container probably isn't going below a certain width so fit keeps it set to some minimum.

**Comment by xiaolannuoyi** [comment] 2021-11-30 03:02
@Tyriar  这不是我的问题，我在测试中发现，`<div class="xterm-viewport" style="background-color: rgb(24, 29, 40); width: 74px;">...</div>` 这里的`style width`始终是页面初始化的width，而且一直不变的。因为这个不变导致屏幕的宽度小于这个宽度就会出现异常
![Nov-30-2021 11-01-07](https://user-images.githubusercontent.com/21079721/143978130-8526f2ec-c388-4f16-9d3c-1de96b5f3439.gif)
。

**Comment by xiaolannuoyi** [comment] 2021-11-30 03:19
`xterm-viewport`. `style  width`
![image](https://user-images.githubusercontent.com/21079721/143979798-ef8a51f4-cfa8-4d26-9a6c-9f989d39b9a2.png)

**Comment by deximy** [comment] 2021-11-30 07:34
I encountered this problem too. I'll try to give a demo which can reproduce this problem.

**Comment by deximy** [comment] 2021-11-30 09:18
Here is a demo: [https://codepen.io/deximy/pen/ZEXExdp](url)
When I open the page with maximum width, everything is ok:
![image](https://user-images.githubusercontent.com/30504323/144015837-6b9fa42b-c1e4-4523-9c89-7bc794ecc079.png)

But when I try to decrease the width, xterm-viewport doesn't change with xterm-screen. It looks like this:
![the left of the page](https://user-images.githubusercontent.com/30504323/144016462-0c53c51b-b827-4eb3-808c-409ff0ece433.png)
↑left of the page
![the right of the page](https://user-images.githubusercontent.com/30504323/144016529-93fb6488-b054-416b-b339-ffbe98b415bb.png)
↑right of the page

The scroll bar is back, and a lot of black space appears on the right of the page.
Here are the attributes of element:
![image](https://user-images.githubusercontent.com/30504323/144017380-90091104-4a16-415d-9d26-b71fe1597f68.png)

I don't know whether if there is a wrong in my use. Please help me for check.

**Comment by Tyriar** [comment] 2021-11-30 16:57
Guess it is an issue on our end. This doesn't happen in vscode because viewport is absolutely positioned such that the scroll bar is right aligned to the container.

**Comment by deximy** [comment] 2021-12-01 04:07
> Guess it is an issue on our end. This doesn't happen in vscode because viewport is absolutely positioned such that the scroll bar is right aligned to the container.

So you mean I need to check some part of the code about the viewport so that I could solve this problem, right?

**Comment by Bryce-huang** [comment] 2021-12-15 15:58
It is irrelevant to this question, is there any usage of native js for addon fit ?

**Comment by Bryce-huang** [comment] 2021-12-15 16:08
It is irrelevant to this question, is there any usage of native js for fit plugin?

**Comment by Tyriar** [comment] 2021-12-16 14:22
@deximy if you want to try fix it yes.

@Bryce-huang it's all js: https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-fit

**Comment by liyuewen** [comment] 2021-12-22 09:41
Use "xterm": "~ 4.10.0", which solves my problem

**Comment by deximy** [comment] 2021-12-24 13:16
> Use "xterm": "~ 4.10.0", which solves my problem

Now I am using "xterm": "^4.15.0". I'll try to downgrade.

**Comment by BitStream1** [comment] 2022-01-03 23:10
I've been running into this issue also. I'm using xterm 4.16.0.

It might be related to the width calculation in Viewport._innerRefresh(), rather than the fit add-on. The width is explicitly calculated based on the number of columns, so the viewport's scrollbar will be aligned to an integer column count rather than the edge of the parent window. e.g.:
```
this._viewportElement.style.width = (this._renderService.dimensions.actualCellWidth * (this._bufferService.cols) + this.scrollBarWidth + (this._lastHadScrollBar ? elementPadding : 0)).toString() + 'px';
```
See: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/src/browser/Viewport.ts#L122

If the number of columns doesn't match the outer xterm's width then the viewport's scrollbar would appear in the middle of the screen. In my case, the main symptom would be the scrollbar appearing before the right edge of the screen, rather than exactly at the end. The scrollbar would also jump when the viewport was resized.

I see that with VS Code, the xterm.js CSS is overridden quite a bit, but I couldn't identify what prevented the manifestation of the issue in VS Code.
https://github.com/microsoft/vscode/blob/17b2d1c97906d4538990ed3ab0200e3fafb98a35/src/vs/workbench/contrib/terminal/browser/media/terminal.css

As a temporary work-around, I only found the following, which effectively disables the above width and has to use an !important:
```
    .xterm .xterm-viewport {
        width: initial !important; 
    }
```
Which leads to the question - does this width really needs to be set and instead use CSS to position viewport, or could there be side effects as a result of removing this?

I hope the extra information may help in resolving the issue.

**Comment by nebbles** [comment] 2022-02-09 19:16
I have also been looking into this. Generally, we were seeing weird resizing behaviour where the term viewport wouldn't match the width of its container (we are also using the addon-fit module).

I was previously on `4.13.0` where there was no issue with the width or resizing. Using a pinned upgrade, I noticed the issue was introduced in `4.14.0`. I have tested all the way up to and including `4.17.0` and the issue remains.

The workaround described by @BitStream1 works to patch this issue (I tested it on `4.14.0` and `4.17.0`)

> ```
> .xterm-viewport {
>     width: initial !important;
> }
> ```

**Comment by enncy** [comment] 2022-03-04 11:09
I got the same problem.
But i found this way, it's work for me : 

```html
<div class="terminal-container">
    <div id="terminal"></div>
</div>
```
```js
import { Terminal } from "xterm";
import { FitAddon } from "xterm-addon-fit";
const term = new Terminal(...);

const fitAddon = new FitAddon();
term.loadAddon(fitAddon);
term.open(document.querySelector("#terminal"));
fitAddon.fit();

window.onresize = function () {
    fitAddon.fit();
};
```

```css
.terminal-container{
    /* fix : https://github.com/xtermjs/xterm.js/issues/3564#issue-1062239799 */
    overflow: hidden;
}
.xterm .xterm-viewport {
    /* see : https://github.com/xtermjs/xterm.js/issues/3564#issuecomment-1004417440 */
    width: initial !important;
}
```

**Comment by KhizerRehan** [comment] 2022-05-13 07:19
Hi, @Tyriar @enncy 
Any help would be appreciated:

I have added xterm-add-on and it is working when placed inside a component within a section
 fitAddon.fit(); spans complete availaible width but i have a requirement built a terminal with just like what GCP provides
 
 and after moving my component to at global postion the  fitAddon.fit(); fails occupy space?
 
 Is it due to custom css applied or any native api approch to do that?
 
 Requirment
![Uploading kuber.png…]()

current:

<img width="1191" alt="xterm" src="https://user-images.githubusercontent.com/17727069/168231836-9b5d1e5a-eadf-403a-9242-ce3f3c82885f.png">
 
 
 
 Any help would be appreciated:
 positon: fixed disrupts all thing :)

**Closed** 2022-05-13 13:07 UTC
Labels: type/bug, help wanted, good first issue

**Comment by makermelissa** [comment] 2022-11-30 22:35
> ```css
> .terminal-container{
>     /* this is important */
>     overflow: hidden;
> }
> .xterm .xterm-viewport {
>     /* see : https://github.com/xtermjs/xterm.js/issues/3564#issuecomment-1004417440 */
>     width: initial !important;
> }
> ```

Thank you. Adding this CSS fixed it for me.
