### ISSUE TITLE
Android chrome - backspace giving previous command history

### ISSUE THREAD

**Issue by sravyak** [xtermjs/xterm.js#4345] opened 2022-12-21 21:40 UTC
I am using ng-terminal in my project. I observed this unexpected behaviour when I use terminal in android chrome. When I backspace in the terminal, I erase previous command input by 1 character and keep going to previous command history.

https://user-images.githubusercontent.com/7556759/209006503-39ebf4e9-1a52-4d2f-b3a7-bc929a2be51e.mp4

## Details
- Browser and browser version: Android Chrome - 109.0.5414.46
- xterm.js version: 5.0.0

### Steps to reproduce

1. open terminal in android chrome
2. Type any command and then try to backspace.

**Comment by Tyriar** [comment] 2022-12-27 14:59
duplicate of https://github.com/xtermjs/xterm.js/issues/3600

**Closed by Tyriar** 2022-12-27 14:59 UTC
