### ISSUE TITLE
Canvas renderer doesn't respect background color changes for spaces

### ISSUE THREAD

**Issue by davidfiala** [xtermjs/xterm.js#4417] opened 2023-02-17 20:46 UTC
When using exclusively the xterm-addon-canvas, changes to background color are not respected if the character(s) immediately following the escape sequence are space characters. Related, if the next character after a background color change is \r, then the entire rest of the line is filled with that background color.

Without canvas, or with just webgl, this bug is not present.

![image](https://user-images.githubusercontent.com/12127027/219787948-cc4bdccb-4e4f-447b-87ea-0e208dda52ce.png)

## Details
- Browser and browser version: FF, Chrome
- OS version: Windows, Linux
- xterm.js version: Head as of this reporting... master @ 9154831afa9aea78306d8edad8fe403616758ad3

### Steps to reproduce

1. Open the xterm demo app. Disable all addons (specifically webgl and canvas)
2. Run: `echo -e "AAA\e[41mRED\e[49mBBB" ; echo -e "CCC\e[41mRED\e[49m   DDD"`
3. Toggle the canvas addon on/off to see the effect.

Note that this applied to any background color, not just default. For example, `echo -e "CCC\e[41mRED\e[42m   DDD\e[49mEND"` will show red before `DDD` even though it should have been green.

`\e[41m`: Set BG color to red
`\e[42m`: Set BG color to green
`\e[49m`: Set BG color to default

**Comment by mrev11** [comment] 2023-02-28 12:36
I can confirm. Loook at this example from the real world. This is htop in xterm.js 5.1.0 with blue background (so that difference will be more spectacular):
![Screenshot from 2023-02-28 13-18-17](https://user-images.githubusercontent.com/23376284/221854246-7342293a-49bb-4d37-a291-2e13b0c66ba6.png)
And the same in the old xterm.js 4.19.0:
![Screenshot from 2023-02-28 13-15-28](https://user-images.githubusercontent.com/23376284/221855019-f814ff8c-bab1-44f7-8450-29253cf2a0c2.png)
Pale colors are adjusted in the second case.

**Comment by Tyriar** [comment] 2023-02-28 15:09
duplicate of https://github.com/xtermjs/xterm.js/issues/4120

**Closed by Tyriar** 2023-02-28 15:09 UTC

**Comment by mrev11** [comment] 2023-03-29 22:44
TextRendererLayer.ts,  line 173.
      // libvte and xterm both draw the background (but not foreground) of invisible characters,    
      // so we should too.                                                                        

DomRendererRowFactory.ts, line 65.
   let lineLength = 0;                                                                             
    for (let x = Math.min(lineData.length, cols) - 1; x >= 0; x--) {                                
      if (lineData.loadCell(x, this._workCell).getCode() !== NULL_CELL_CODE || (isCursorRow && x ===
        lineLength = x + 1;                                                                         
        break;                                                                                      
      }                                                                                             
    }   
This code cuts lines ending with invisible charactres.
