### ISSUE TITLE
OSX qwertz keyboard dead keys

### ISSUE THREAD

**Issue by hjanuschka** [xtermjs/xterm.js#2023] opened 2019-04-25 11:34 UTC
using kubernetes dashboard -> https://github.com/kubernetes/dashboard/issues/3759

i am unable to enter for example `|`  as it requires me to press `OPTION+7`  and xterm does not get it! (tested on the demo site too)

**Comment by jerch** [comment] 2019-04-26 09:02
@hjanuschka Can you repro this outside of k8s dashboard, e.g. with xterm's demo as well? If so I wonder if your OS settings (browser doesnt get the right key event) cause this. `|` is a very common char to input in the terminal and we got no reports like this so far.

**Comment by hjanuschka** [comment] 2019-04-26 09:24
i can repro it on https://xtermjs.org/

cannot enter characters that require the OSX OPTION key as a prefix. i don't have any special keyboard settings, only german (qwertz) standard osx keyboard.


also having the problem on hterm, pretty weird, forces me to create OPTION characters in the url-bar and the copy pasting them back into xterm


any idea, on how i can debug this?


on, a desktop application (https://github.com/kovidgoyal/kitty) there was a similar problem, and they added a option `macos_option_as_alt`

**Comment by Tyriar** [comment] 2019-04-26 18:11
Maybe this setting is what you're after?

https://github.com/xtermjs/xterm.js/blob/c6f785f51a987de3d76219172f581a645e64e6ec/typings/xterm.d.ts#L134-L137

Not sure if the Kubernetes dashboard exposes that but you can test in the demo by checking the option before the terminal.

**Comment by hjanuschka** [comment] 2019-04-26 18:38
https://codesandbox.io/s/j380qm2j3


hmmm with `true`  on that option, the `|` is shown nowhere, when setting it to false, it is not shown in the `terminal` div, but in the textarea above it is shown.

**Comment by Tyriar** [comment] 2019-04-27 23:45
@jerch any thoughts here? Not sure if you use qwertz or not?

**Comment by jerch** [comment] 2019-04-28 09:45
@Tyriar I cannot test it myself, have only access to a qwerty MBP. Furthermore I am stil not convinced that this is a general problem - I think we would have seen much more bug requests if it would happen with all qwertz apple notebooks. Maybe @mofux has a qwertz device and can double check this?

**Comment by mofux** [comment] 2019-04-28 16:33
I can reproduce the problem in the terminal on xtermjs.org (MacOS, qwertz keyboard), but it is working correcly with the current demo build from master. As far as I can remember I've never had issues with this in a regular xterm.js session connected to node-pty. @hjanuschka I guess none of the characters that require you pressing the `option` key work for you (e.g. `@` or `{` or `}`)? @jerch @Tyriar does pressing `option + 3` on the xtermjs.org demo site insert a `£` character with your US keyboards? It doesn't work for me. @hjanuschka Are you using the regular MacOS `bash` or some other shell?

**Comment by Tyriar** [comment] 2019-04-29 19:17
It inserts a `£` for me when macOptionIsMeta is false, when true I get `(arg: 3) `

**Comment by hjanuschka** [comment] 2019-04-29 22:21
@mofux yes none of the OPTION based characters work

**Comment by Tyriar** [comment] 2019-04-29 23:17
Just realized you said demo site, it doesn't do anything on the demo site for me, but that's probably because of https://github.com/xtermjs/xtermjs.org/blob/ece844ae216305765f870dadada74c0b9a012a13/js/demo.js#L23

**Comment by hjanuschka** [comment] 2019-04-30 11:13
here is a video of the problem: https://youtu.be/Dso3pYvF4j4


i tried to add a `|` after the echo.

**Comment by mofux** [comment] 2019-04-30 11:30
This clearly looks like a locale problem to me. My guess would be that the remote shell is operating on a different locale than your keyboard, causing a misinterpretation of the command that is being sent. Can you post the output of the `locale` command, as well as the `env` command? You might want to sanitize sensible output of the `env` command first.

**Comment by hjanuschka** [comment] 2019-04-30 12:30
locale:

```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
```


env
```
TERM=xterm
KUBERNETES_SERVICE_PORT=443
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/usr/share/keymaps/i386/qwertz
LANG=C.UTF-8
SHLVL=1
HOME=/root
DEBIAN_FRONTEND=noninteractive
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s

```

i am pretty sure the keyboard layout is korrekt, if press `z` it should result in a `y` if it was a english keyboard :/

**Comment by mofux** [comment] 2019-04-30 12:43
Strange, does it print the `ö`, `ß` and `ä` characters correctly?

**Comment by hjanuschka** [comment] 2019-04-30 13:19
@mofux thats weird, `z` and `y` are correct, but `ö` and co. are broken
![Bildschirmfoto 2019-04-30 um 15 19 19](https://user-images.githubusercontent.com/2891702/56964373-5abc5a00-6b5b-11e9-97fd-39dba6d29ad4.png)



what a weird problem, i tried on my macbook, with almost 100% stock settings, same error.

**Comment by mofux** [comment] 2019-04-30 15:01
Yeah I still think this is related to the locale in the docker container differing from your OS's keyboard setting. Let me close this thread as I think there is nothing xterm.js can do about it, but I'll post another update with some thoughts in your kubernetes dashboard issue.

**Closed by mofux** 2019-04-30 15:01 UTC
Labels: needs more info

**Comment by hjanuschka** [comment] 2019-04-30 15:21
LANG is not the problem tbh but i am fine with closing it, just going to use console based k8s terminal

![Bildschirmfoto 2019-04-30 um 17 20 58](https://user-images.githubusercontent.com/2891702/56973053-649a8900-6b6c-11e9-9fa7-645a4d22e2bb.png)

**Comment by mofux** [comment] 2019-04-30 16:28
> i did expect to xterm.js to abstract the container settings, like when docker exec also uses my local keyboard settings

`docker exec` can read your local environment and then pass it to the docker api when attaching to a container, but this is a lower level. I'm running xterm.js against different backends (node-pty, ssh2, docker) also using a qwertz layout on Mac, and I only ever see these kind of problems happen if there is a disagreement between the target environment and the user's locale. I'm sure if you use vscode's terminal locally (which also uses xterm.js) you won't see these problems. Don't get me wrong, I don't want to close you off, but I really think there is nothing we can do from our side apart from helping the kubernetes dashboard maintainers with some clues.

**Comment by hjanuschka** [comment] 2019-04-30 18:02
no worries, i am fine, but yet is cannot be related to the docker/remote whatever, since i also cannot enter a `|`  in the embeded example: https://xtermjs.org/ (which uses some kind of dummy repl)

**Comment by hjanuschka** [comment] 2019-04-30 18:06
i am trying to find this: https://codesandbox.io/s/j380qm2j3
forcing printable to `true` - alerts "key: 7`  instead of `key: |` - so i am now quiet confident it is not the docker remote or something like that

**Comment by hjanuschka** [comment] 2019-04-30 18:10
https://codesandbox.io/s/j380qm2j3 with `{ macOptionIsMeta: false }` and always `printable` the demo works 👏  now diving into the K8s dashboard.

**Comment by mofux** [comment] 2019-04-30 19:18
Btw. `{ macOptionIsMeta: false }` is the default anyway, so leaving the option unset should work as well.
