### ISSUE TITLE
Chinese special characters are displayed twice

### ISSUE THREAD

**Issue by zhangyu19940118** [xtermjs/xterm.js#3196] opened 2020-12-28 08:00 UTC
In the Chinese input method environment, input special characters, it will be displayed twice.

## Details
- Browser and browser version: Chrome87
- OS version: Windows10
- xterm.js version: 4.9.0

### Steps to reproduce

1. open Terminal
2. Switch to Chinese input method
3. input special characters，eg：-; %; （）;

**Comment by kena0ki** [comment] 2020-12-29 13:18
This is a duplicate of #3191.

**Comment by mofux** [comment] 2020-12-31 13:49
Let's close this issue in favour of #3191.

**Closed by mofux** 2020-12-31 13:49 UTC
