### ISSUE TITLE
Tall characters have their top and/or bottom cut off

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1138] opened 2017-12-11 11:19 UTC
This applies to tall g's and some other characters on some fonts and also to diacritical marks in various languages.

VS Code issue: https://github.com/Microsoft/vscode/issues/35901

**Comment by Tyriar** [comment] 2017-12-14 20:40
This is by far the most reported issue against the terminal in VS Code

**Comment by Jeyanthinath** [comment] 2018-01-10 18:22
@Tyriar Can you do it a bit quicker as it is nearly impossible to use vscode for `demos` as it is very hard to explain the audience about the _ is hidden.

It really hurts the daily usage. :(

**Comment by Tyriar** [comment] 2018-01-11 17:48
@Jeyanthinath I'm busy dealing with accessibility at the moment. There are several workarounds mentioned in https://github.com/Microsoft/vscode/issues/35901 (change font size, change font family)

**Comment by ioquatix** [comment] 2018-05-08 11:56
Is this the issue we are having here? https://github.com/ioquatix/script-runner/issues/93#issuecomment-387372030

**Comment by Tyriar** [comment] 2018-05-11 16:57
@ioquatix I noticed there may be issues with the default 18.04 Ubuntu font. It may be the similar https://github.com/xtermjs/xterm.js/issues/1170

**Comment by segevfiner** [comment] 2018-08-06 22:38
This reproduces with [DejaVu Sans Mono for Powerline](https://github.com/powerline/fonts/tree/master/DejaVuSansMono), and also likely with the normal DejaVu Sans Mono, at 14px, using the canvas renderer. Which is the default configuration in VS Code on Ubuntu 16.04, and likely others.

The problem seems to be that [`Element.getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) in chromium returns `height` off by one:
```js
JSON.stringify(term._core.charMeasure._measureElement.getBoundingClientRect())
{"x":-139870,"y":81.875,"width":8.4375,"height":16,"top":81.875,"right":-139861.5625,"bottom":97.875,"left":-139870}
```

In Firefox:
```js
// Grrrr: https://bugzilla.mozilla.org/show_bug.cgi?id=1100611
term._core.charMeasure._measureElement.getBoundingClientRect()
DOMRect { x: -139592, y: 86.86666870117188, width: 8, height: 17, top: 86.86666870117188, right: -139584, bottom: 103.86666870117188, left: -139592 }
```

This simple hack fixes this, but it will also result in `height` being one pixel larger when the `getBoundingClientRect` does return the correct result. So it's not really a fix, just a way to prove this is really the problem.
```diff
diff --git a/src/ui/CharMeasure.ts b/src/ui/CharMeasure.ts
index 5ad1de7..7be6d83 100644
--- a/src/ui/CharMeasure.ts
+++ b/src/ui/CharMeasure.ts
@@ -48,7 +48,7 @@ export class CharMeasure extends EventEmitter implements ICharMeasure {
     }
     if (this._width !== geometry.width || this._height !== geometry.height) {
       this._width = geometry.width;
-      this._height = Math.ceil(geometry.height);
+      this._height = Math.ceil(geometry.height + 1);
       this.emit('charsizechanged');
     }
   }
```

Maybe there is a way to get Chromium to return the correct result here (Different measurement character, CSS style, etc.), or maybe there is an alternative way to calculate this metric which is more reliable.

Versions:
xterm.js master at 3419480
Chromium 68.0.3440.75
Firefox 61.0.1
Ubuntu 16.04.5 x64

P.S. I added [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) locally to the webpack setup so that I would be able to debug the demo in the browser. Might want to consider this for the committed setup.

**Comment by Tyriar** [comment] 2018-08-07 18:59
@segevfiner I see this issue in Chrome as well, where the selection does not include all the text. If Chrome turns on [advanced TextMetric props](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics) we might be able to fix it by using that instead of DOM to measure.

**Comment by Tyriar** [comment] 2018-08-07 19:00
@segevfiner if `source-map-loader` fixes source maps in the demo, yes please! :heart_eyes:

**Comment by segevfiner** [comment] 2018-08-07 19:55
> @segevfiner if source-map-loader fixes source maps in the demo, yes please! 😍

https://github.com/xtermjs/xterm.js/pull/1601

**Comment by segevfiner** [comment] 2018-08-07 20:09
> @segevfiner I see this issue in Chrome as well, where the selection does not include all the text. If Chrome turns on advanced TextMetric props we might be able to fix it by using that instead of DOM to measure.

It will probably take some time for this API to stabilize. Maybe some polyfill or some library implemented a measurement technique that works... Maybe https://github.com/motiz88/canvas-text-metrics-polyfill or https://www.npmjs.com/package/text-metrics (There are likely more). Needs testing to see if any library gets it right.

**Comment by Tyriar** [comment] 2018-08-07 21:20
@segevfiner good to know. I was actually putting something together that's very similar to that for text measuring the other week (`getImageData` and analysing pixels). I won't have time to look at it again for a while, but that's good validation that this is the right direction.

**Comment by segevfiner** [comment] 2018-08-08 07:01
I tried enabling "Experimental Web Platform features" and checking if we can get the correct value from it, but it seems like even that API returns a value that is one pixel short.

![image](https://user-images.githubusercontent.com/24731903/43821288-6f1cf864-9af1-11e8-91ff-94e4f0bc153b.png)

The used test code: [textmetrics-test.zip](https://github.com/xtermjs/xterm.js/files/2269207/textmetrics-test.zip)

P.S. Wow... The property names they choose for these are quite obscure. 😖

**Comment by Tyriar** [comment] 2018-08-08 14:51
@segevfiner if that's buggy too I guess it needs to Chrome bug to get fixed first.

Not sure I could come up with better names for 12 things that describe a bounding box 😉

**Comment by zwhitchcox** [comment] 2018-11-29 19:39
Is there any progress on this?This happens for me in chrome and firefox

**Comment by Tyriar** [comment] 2018-11-29 22:09
@zwhitchcox it's fixed in https://github.com/xtermjs/xterm.js/pull/1790, this probably won't ship for some time though.

**Comment by martin31821** [comment] 2018-12-05 12:58
Seeing this in chromium 71 as well now :(

**Closed** 2019-06-23 20:28 UTC
Labels: area/renderer, type/bug

**Comment by Tyriar** [comment] 2019-06-23 20:30
This issue was closed off as it's fixed in the experimental WebGL renderer addon. It's not ready yet but I'm closing this off so I don't forget about it. See this query for current webgl addon issues https://github.com/xtermjs/xterm.js/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Faddon%2Fwebgl
