### ISSUE TITLE
Publish with ecmascript module exports

### ISSUE THREAD

**Issue by tracker1** [xtermjs/xterm.js#3182] opened 2020-11-25 16:26 UTC
I'm wanting to reference the modules directly via unpkg and was trying to use module imports in a browser JS module...

```js
import { Terminal } from 'https://unpkg.com/xterm@4.9.0/lib/xterm.js';
import { WebLinksAddon } from 'https://unpkg.com/xterm-addon-web-links@0.4.0/lib/xterm-addon-web-links.js';
import { FitAddon } from 'https://unpkg.com/xterm-addon-fit@0.4.0/lib/xterm-addon-fit.js';
```

However, the esm export statements aren't part of the published modules.  Would be nice to ether have `.mjs` references or include them in the published module(s).

**Comment by jerch** [comment] 2020-11-26 00:55
Plz read [this document](https://xtermjs.org/docs/guides/security/) about possible security implications with CDNs.

**Comment by tracker1** [comment] 2021-01-14 01:42
@jerch It's less about the security implications as being able to use this directly in the browser without having to use a separate bundler.

Using unpkg isn't significantly better/worse than using npm to receive these modules.  From the POV of this project, it's likely a small configuration change.

**Comment by jerch** [comment] 2021-01-14 02:22
> Using unpkg isn't significantly better/worse than using npm to receive these modules.

I strongly disagree. NPM is the package repo we directly push our builds to, the service itself is an important and well-tested part of the whole JS ecosystem. These 2 facts make it much more trustworthy than some random CDN. For xterm.js normal web dev security standards are not enough, dealing with shell access raises the bar significantly.

Ofc this is only loosely coupled to your issue topic (which raises a valid point), still I think we should not feed a bad habit by making the unsecure way even easier.

**Comment by Tyriar** [comment] 2021-01-14 14:28
duplicate of https://github.com/xtermjs/xterm.js/issues/2878

**Closed by Tyriar** 2021-01-14 14:28 UTC
