### ISSUE TITLE
.xterm-char-measure-element Dom width  & height calculation error

### ISSUE THREAD

**Issue by opopeieie** [xtermjs/xterm.js#3160] opened 2020-10-30 11:16 UTC
Can we change the getBoundingClientRect method under /browser/services/CharSizeService.ts to offsetWidth or offsetHeight to get the width and height?? cuz sometimes the getBoundingClientRect and Timeout do not get the width and height correctly

**Comment by Tyriar** [comment] 2020-10-30 14:29
I haven't seen any issues with this, is it a browser bug you're hitting? We need some more information on how to repro.

**Comment by opopeieie** [comment] 2020-11-02 06:33
Oh....Here is the case: https://codesandbox.io/s/nifty-hill-1i7wz?file=/src/App.js ,When the style is set to transform: scale, xter uses the "getBoundingClientRect" with the wrong length and width, offset is normal

**Comment by Tyriar** [comment] 2020-11-02 13:07
I don't think we care that much about this edge case, but maybe it could be improved by using `ResizeObserver` if it's available?

**Comment by mofux** [comment] 2020-11-02 13:26
I think the problem is that `getBoundingClientRect()` provides the dimensions with transformations applied, whereas `offsetHeight` and `offsetWidth` provides the original dimensions without the transformations. In that sense, I would agree that using `offsetHeight` and `offsetWidth` is preferable over `getBoundingClientRect()` for our use-case. Still, as @Tyriar already stated, this is a very minor edge case.

I (only speaking for myself) would be open towards a PR that changes the measure from `getBoundingClientRect()` to `offsetHeight` and `offsetWidth`.

**Comment by Tyriar** [comment] 2020-11-02 13:44
👍 if they're functionally equivalent outside of that

**Comment by opopeieie** [comment] 2020-11-02 14:02
My current solution is to give up transform animation, if it can be changed, it’s really great!🙂🙃

**Comment by Tyriar** [comment] 2022-12-15 15:59
duplicate of https://github.com/xtermjs/xterm.js/issues/2488

**Closed by Tyriar** 2022-12-15 15:59 UTC
Labels: type/bug, help wanted
