### ISSUE TITLE
Firefox renders characters in the wrong position (v3)

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1055] opened 2017-10-11 17:59 UTC
**xterm.js v3**

In Firefox, the text inside the cursor is not aligned centered:

Firefox: 
<img width="160" alt="screen shot 2017-10-11 at 19 50 23" src="https://user-images.githubusercontent.com/2785983/31457684-c6f07a6e-aebd-11e7-8a7d-52b652194f8c.png">

Chrome (expected):
<img width="157" alt="screen shot 2017-10-11 at 19 50 36" src="https://user-images.githubusercontent.com/2785983/31457686-cbbabd20-aebd-11e7-9ddf-aa0572e0e519.png">

Same goes for background:

Firefox: 
<img width="740" alt="screen shot 2017-10-11 at 19 55 32" src="https://user-images.githubusercontent.com/2785983/31457869-72515ad6-aebe-11e7-8a52-dc4c24aa9d23.png">

Chrome (expected):
<img width="730" alt="screen shot 2017-10-11 at 19 56 00" src="https://user-images.githubusercontent.com/2785983/31457878-78ca76cc-aebe-11e7-9570-eac599037492.png">

**Comment by mofux** [comment] 2017-10-11 18:51
Firefox seems to report different values from the CharMeasure (running the default demo):

FF:
```json
{
  "scaledCharWidth": 18,
  "scaledCharHeight": 32,
  "scaledLineHeight": 32,
  "scaledLineDrawY": 0,
  "scaledCanvasWidth": 1566,
  "scaledCanvasHeight": 896,
  "canvasWidth": 783,
  "canvasHeight": 448,
  "actualCellWidth": 9,
  "actualCellHeight": 16
}
```

Chrome:
```json
{
  "scaledCharWidth": 18,
  "scaledCharHeight": 34,
  "scaledLineHeight": 34,
  "scaledLineDrawY": 0,
  "scaledCanvasWidth": 1548,
  "scaledCanvasHeight": 884,
  "canvasWidth": 774,
  "canvasHeight": 442,
  "actualCellWidth": 9,
  "actualCellHeight": 17
}
```

**Comment by Tyriar** [comment] 2017-10-11 23:51
Maybe textBaseline top doesn't work on FF?

https://github.com/sourcelair/xterm.js/blob/b6c886837f7fddd75de2a0b320ec448c34193810/src/renderer/BaseRenderLayer.ts#L277

**Comment by mofux** [comment] 2017-10-12 11:55
Already tried to toggle through the available textBaseline values, it does funny things, but doesn't fix the problem 😕

**Comment by Tyriar** [comment] 2017-11-05 19:58
Looks like the root cause is the DOM height measurement in `CharMeasure` is coming back as 17 in Chrome and 16 in Firefox. Would be good to fix but I don't think this is a blocker for v3.

**Comment by Tyriar** [comment] 2018-09-17 17:29
Closing this off as I think it's Firefox misbehaving

**Closed by Tyriar** 2018-09-17 17:29 UTC
Labels: area/renderer, browser/firefox, type/bug
