### ISSUE TITLE
Previous output leeches through to nvim w/ WebGL Addon enabled

### ISSUE THREAD

**Issue by AlexMordred** [xtermjs/xterm.js#3878] opened 2022-06-29 10:56 UTC
Previous commands' output leeches through to nvim. The old output is only visible on the same lines you see the nvim prompt text - see screenshot. Doesn't happen with other editors, tried `vi`, `nano`, `micro`. Only happens when using the WebGL Addon. 

## Details
- Browser and browser version: Firefox 101.0.1
- OS version: Linux 5.15.49-1-MANJARO
- xterm.js version: latest

### Steps to reproduce

1. Run some commands until at least half of your screen is filled with output bottom to top
2. Run `nvim`

![image](https://user-images.githubusercontent.com/8043551/176419989-2e8699e3-507a-42ed-a27e-972ccf9dad24.png)

**Comment by Tyriar** [comment] 2022-07-05 13:08
I've spotted something similar recently as well

**Comment by Tyriar** [comment] 2022-07-10 21:48
These dots are what I've seen sometimes:

<img width="362" alt="Screen Shot 2022-07-10 at 2 48 01 pm" src="https://user-images.githubusercontent.com/2193314/178163196-6723d0c8-5b7f-4e6a-aa3e-c18e72027c9b.png">

I don't know the repro and I can't repro with nvim on macOS or Windows.

**Comment by AlexMordred** [comment] 2022-07-11 01:27
@Tyriar I don't know much about terminals, but mine is a default Manjaro Linux terminal and yours looks customized (`.bashrc`?), I guess that makes a difference too.

**Comment by Tyriar** [comment] 2022-07-11 12:30
@AlexMordred good point, I'll check without the fancy prompt

**Comment by Tyriar** [comment] 2022-07-18 18:39
We're a bit too busy to action this issue in July

**Comment by Tyriar** [comment] 2022-07-29 00:06
I don't have a Linux machine but I tested on the latest `master` of xterm.js on macOS in Firefox and Edge and seems to work fine. Some more information that could help:

- `echo $PS1` result
- Set log level to debug and provide the logs when reproducing

**Comment by AlexMordred** [comment] 2022-07-30 11:35
```
$ echo $PS1
\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\]
```

Not sure I understand the second part

**Comment by Tyriar** [comment] 2022-07-30 12:58
@AlexMordred you an turn debug logs on which get send to the devtools console by running `term.options.logLevel = 'debug'`

**Comment by JasonXJ** [comment] 2022-08-22 04:10
Hi, I believe I have hit the same bug, although the symtom is a bit different. And I have a way to reliably reproducing it on either xterm.js 4.19.0 or vscode 1.70.2 (linux) when webgl is enabled (canvas without webgl does not have the same issue).

```
$ echo '\u26a1\u26a1123' | tee /tmp/test
$ nvim -u NONE /tmp/test
```
And when you are in neovim, do this, `A<esc>A<esc>:q!`. On the status line, you will see this:

![Screenshot 2022-08-21 8 37 36 PM](https://user-images.githubusercontent.com/6949499/185836489-e872603f-25c7-4567-8339-4f6384b5f5b3.png)

The text `INSERT --` should have been cleared (it is cleared when webgl is disabled).

--------

I also see another issue in my xterm.js but not in vscode --- my `\u26a1` is displayed one-char wide although neovim seems to consider it two-char wide (see the cursor position in this screenshot):

![Screenshot 2022-08-21 8 37 00 PM](https://user-images.githubusercontent.com/6949499/185837467-0f25305c-3338-41a6-9685-d0f260d7137f.png)

vscode seems to always display it two-char wide:

![image](https://user-images.githubusercontent.com/6949499/185837556-c7065fde-7014-4d48-964e-3ce78d771037.png)

This does not seem to be affected by the font-family or whether webgl is enabled. Do you know why?

**Comment by JasonXJ** [comment] 2022-08-22 07:43
I also find a way to repro a rendering error similar to this [comment](https://github.com/xtermjs/xterm.js/issues/3878#issuecomment-1179805904). I think it is actually an issue different from the one in my last comment.

So, you can trigger this error by:

- create a file with box drawing symbols \u2592 (e.g. `python3 -c 'print("\u2592"*20)' > /tmp/boxes`);
- use vim to open it (I don't think it actually has anything to do with vim though)
- Move the cursor back and forth
- You might need to switch the color scheme to see the rendering error.

![Peek 2022-08-22 17-31](https://user-images.githubusercontent.com/6949499/185865131-186a9952-125f-4c63-a708-33f20eb8d68f.gif)

**Comment by JasonXJ** [comment] 2022-09-05 07:25
So, there are actually two different bugs mentioned here: 1) the issue mentioned by OP and [this comment](https://github.com/xtermjs/xterm.js/issues/3878#issuecomment-1221782722), where some texts are not cleared correctly and 2) Rendering artefects (e.g. dots) on the cursor canvas.

I figured out what is wrong with 1. It can happen when neovim sets some colors and then deletes some characters, and this is what happens inside the `WebglRenderer`:
* `setColors()` is called, and it clears `this._model` but not `this._glyphRenderer`.
* `_updateModel()` is called to update `this._model` to match the terminal buffer. Because `this._model` was cleared earlier, the code [here](https://github.com/xtermjs/xterm.js/blob/93bc9bf1525f663fda72c7637ae0366c2e5a9868/addons/xterm-addon-webgl/src/WebglRenderer.ts#L420) thinks that the cell is up-to-date and there is no need to update `this._glyphRenderer`.

I think the correct fix for this is to make sure we clear `this._glyphRenderer` when we clear `this._model`. I will send a pull request soon.

**Comment by Tyriar** [comment] 2022-09-12 15:18
I think this is fixed as both of @JasonXJ's PRs were merged. Correct me if I'm wrong 🙂

**Closed by Tyriar** 2022-09-12 15:18 UTC
Labels: type/bug, needs more info, area/addon/webgl

**Comment by deadb0d4** [comment] 2022-09-20 19:16
@Tyriar that's a silly question, but when do you roughly expect these changes to be in vscode (stable version)?

**Comment by Tyriar** [comment] 2022-09-22 13:51
@deadb0d4 I think this was landing in 1.72 (early October)
