### ISSUE TITLE
Cutting off bottom of characters in Firefox

### ISSUE THREAD

**Issue by hvisage** [xtermjs/xterm.js#3555] opened 2021-11-14 22:06 UTC
## Details
- Browser and browser version: FireFox 94.0.1 (64-bit) 
- OS version: macOS (And reports of Linux)
- xterm.js version:  4.12.0-1    (ProxMox PVE 6 & 7's pve-xtermjs    4.12.0-1     amd64        HTML/JS Shell client for Proxmox projects)

### Steps to reproduce

1. login to ProxMox PVE
2. open a shell (hypervisor) or console (xterm.js for especially LXC)
3. type the underscore _ or j and compare to Chrome. the underscore (_) characters "disappears"

FireFox:
![image](https://user-images.githubusercontent.com/11662665/141700444-134fb8c0-88df-43d5-abb3-af72512be41d.png)

MS-Edge:
![image](https://user-images.githubusercontent.com/11662665/141700448-f2856dc1-393e-408d-9f9b-ac793821c2d7.png)

Further reports at https://forum.proxmox.com/threads/xterm-js-cutting-off-characters-in-firefox.92782/

**Comment by Tyriar** [comment] 2021-12-21 18:10
duplicate of https://github.com/xtermjs/xterm.js/issues/3353

**Closed by Tyriar** 2021-12-21 18:10 UTC
