### ISSUE TITLE
unkown escape characters

### ISSUE THREAD

**Issue by veeramarni** [xtermjs/xterm.js#1770] opened 2018-10-25 22:04 UTC
In some scenarios a terminal page that connects to a existing pty process that running a nodejs or some commands in-progress, we noticing few escape character that is been sent to backned. 

We trying to understand what those means, as those are not filtered they are sent back to frontend and we see them as junk characters.

```
[5;52R
[3;52R
[1;52R
[19;52R
[19;52R
[19;52R
[19;88R
```

We couldn't determine ourself as we are not sending that `text` from our end, so it seems like something from xterm doing it internally. If you could guide us what those escape character means and how can we avoid showing in the UI.

## Details
- Browser and browser version: Chrome 
- OS version: MacOs
- xterm.js version: 3.4.1

**Comment by jerch** [comment] 2018-10-26 04:20
@veeramarni Those are cursor position reports, they will be sent by the emulator after a device status request. Means some program you are using requests cursor positions. If those are not consumed they stack up in STDIN until some later program reads STDIN (a shell would also echo it back to the emulator since it treats STDIN as user input).

**Comment by theflyingape** [comment] 2018-11-02 13:29
Yes, looks like this example is [querying](http://www.cse.psu.edu/~kxc104/class/cmpen472/11f/hw/hw7/vt100ansi.htm) for a **report cursor position** whereas the emulator responds back with this coded sequence; but, it is not being 'consumed' by the app properly... so it is being echoed (modified?) back to the emulator.  What is your host's TERM set which could be affecting the app's ability to query?

That being said, `echo -en '\x1b[5;52R'` or the like _should_ get consumed by the emulator resulting in a case default NOP.  This is widely acceptable behavior and my xterm.js test does not echo any junk:
```
$ echo $TERM
xterm-256color
$ echo -en '\x1b[6n'; read -s -n 15 -t 1 c
$ echo -n $c | hexdump -C
00000000  1b 5b 33 30 3b 31 52                              |.[30;1R|
00000007
$ echo $c
```

**Comment by veeramarni** [comment] 2018-11-02 18:01
@theflyingape 


Here is my output. We see the junk, porbably we need to set TERM to `screen` or something, we will test it. 
```
/usr/src/app # echo $TERM
xterm
/usr/src/app # echo -en '\x1b[6n'; read -s -n 15 -t 1 c
/usr/src/app #  echo -n $c | hexdump -C
/usr/src/app # echo $c

/usr/src/app #
```

**Comment by jerch** [comment] 2018-11-02 19:06
@veeramarni More info would be helpful, what program you are using and such. Normally a program that requests cursor positions should be prepared to handle the response, so the garbage should not make it back to the emulator. Is there some kind of tty multiplexing involved? Maybe the underlying pty termios settings should be set to echo off?

**Comment by jerch** [comment] 2018-11-14 22:31
Closing the issue since it is not caused by xterm.js.

**Closed by jerch** 2018-11-14 22:31 UTC
Labels: needs more info
