### ISSUE TITLE
Terminal always show uppercase letters when using caps lock to switch input source

### ISSUE THREAD

**Issue by jasonxia23** [xtermjs/xterm.js#3155] opened 2020-10-29 04:18 UTC
## Details
- Browser and browser version: Found in VSCode 1.50.1, I think it's browser unrelated.
- OS version: 10.15.7
- xterm.js version: Found in VSCode 1.50.1, I think it's xterm.js version unrelated.

### Steps to reproduce

1. Set system input source to shuangpin, before which add shuangpin as an input source.
![image](https://user-images.githubusercontent.com/15098719/97403011-97bf0380-192e-11eb-90a8-5c2f551a17cb.png)
2. Lock caps lock, with caps lock unlock, you will input Chinese character, which is an expected behavior.
3. Input something in the terminal, I can only input upper case letters. But when I input something in some other application, I can input lower case letters.

**Comment by gqbre** [comment] 2021-04-08 08:12
same issue：https://github.com/xtermjs/xterm.js/issues/2457

**Comment by Tyriar** [comment] 2022-06-26 16:27
duplicate of https://github.com/xtermjs/xterm.js/issues/2457

**Closed by Tyriar** 2022-06-26 16:27 UTC
Labels: type/bug, help wanted, area/ime
