### ISSUE TITLE
French keyboard layout can't handle input tilde (~)

### ISSUE THREAD

**Issue by ComeBurguburu** [xtermjs/xterm.js#3570] opened 2021-12-06 12:00 UTC
![image](https://user-images.githubusercontent.com/10062185/144841823-fbfbf1eb-fcdf-4063-a9a9-87e08d54a4b3.png)

When french keyboard in chrome I can't write `~` it output `é` 
Same issue with ``` which input `è`
Please note that normaly `~` or ``` are waiting for extra character before print

## Details
- Browser and browser version: Chrome (latest), work in firefox
- OS version: Ubuntu 
- xterm.js xterm@4.9.0, xterm-addon-fit@0.4.0, term-addon-web-links@0.4.0

NB: xterm 4.9 is used in RStudio 1.4 in this case

### Steps to reproduce

1. When pressing altGr+2 got é
2. When pressing altGr + 2 two times got `é~é~`

![image](https://user-images.githubusercontent.com/10062185/144841280-ab7aa918-7c4e-47ee-be5c-fe32bddd164c.png)

Related bugs:
#174

**Comment by Tyriar** [comment] 2021-12-20 18:36
duplicate of https://github.com/xtermjs/xterm.js/issues/2151

**Closed by Tyriar** 2021-12-20 18:36 UTC
