### ISSUE TITLE
Unrelated texts merge to each other when using vim

### ISSUE THREAD

**Issue by MajidSadrr** [xtermjs/xterm.js#3829] opened 2022-05-25 10:30 UTC
Hi. When I open xterm.js terminal and open vim, an issue happens is scrolling with enter key or arrow key. white texts placed in the right of the pictures merge with file opened with vim. I couldn't find if problem is with my code or some issues in xterm.js.

## Details
- browser: Firefox 100 
- xterm.js version: 4.18.0

![image](https://user-images.githubusercontent.com/76779095/170241176-50aeed63-0015-4a06-a93e-ed7a5162a7f7.png)

### Steps to reproduce

1. Make sure there is scrollable content on the terminal.
2. Start `vim FILENAME`.
3. Scroll with pressing enter and then down arrow key.

**Comment by idropwater** [comment] 2022-07-28 08:03
it happen when screen scaling not 100%

**Comment by idropwater** [comment] 2022-07-28 10:36
> Hi. When I open xterm.js terminal and open vim, an issue happens is scrolling with enter key or arrow key. white texts placed in the right of the pictures merge with file opened with vim. I couldn't find if problem is with my code or some issues in xterm.js.
> 
> ## Details
> * browser: Firefox 100
> * xterm.js version: 4.18.0
> 
> ![image](https://user-images.githubusercontent.com/76779095/170241176-50aeed63-0015-4a06-a93e-ed7a5162a7f7.png)
> 
> ### Steps to reproduce
> 1. Make sure there is scrollable content on the terminal.
> 2. Start `vim FILENAME`.
> 3. Scroll with pressing enter and then down arrow key.



> Hi. When I open xterm.js terminal and open vim, an issue happens is scrolling with enter key or arrow key. white texts placed in the right of the pictures merge with file opened with vim. I couldn't find if problem is with my code or some issues in xterm.js.
> 
> ## Details
> * browser: Firefox 100
> * xterm.js version: 4.18.0
> 
> ![image](https://user-images.githubusercontent.com/76779095/170241176-50aeed63-0015-4a06-a93e-ed7a5162a7f7.png)
> 
> ### Steps to reproduce
> 1. Make sure there is scrollable content on the terminal.
> 2. Start `vim FILENAME`.
> 3. Scroll with pressing enter and then down arrow key.

Is this problem solved please?

**Comment by idropwater** [comment] 2022-07-28 10:37
Is this problem solved please?

**Comment by MajidSadrr** [comment] 2022-07-28 12:11
Not yet, but I'm going to try scaling terminal to 100% to see if it solves or not.

**Comment by Tyriar** [comment] 2022-07-30 13:28
duplicate of https://github.com/xtermjs/xterm.js/issues/3878

Please add any additional information there that could help with a repro there

**Closed by Tyriar** 2022-07-30 13:28 UTC
Labels: needs more info
