### ISSUE TITLE
Can not run demo on Windows

### ISSUE THREAD

**Issue by lonelywolf4git** [xtermjs/xterm.js#1014] opened 2017-09-30 03:02 UTC
I can not run demo on windows and found the same issue https://github.com/sourcelair/xterm.js/issues/562
From the readme: 
"Windows
First, ensure node-gyp is installed and configured correctly, then run these commands."
I do install  node-gyp with writing this dependency in package.json.
From the issue [https://github.com/sourcelair/xterm.js/issues/562](url)   "You need to install the dependencies of the https://github.com/rprichard/winpty project".  I am confusing that how to compile winpty? Using node-gyp to build it? or something else?   So I will appreciate it if you give me one guide step by step. thanks for patience!

**Comment by Tyriar** [comment] 2017-09-30 09:30
@lonelywolf4git I think Visual Studio 2015/2017 is the main dependency here. Do you have that installed?

**Comment by lonelywolf4git** [comment] 2017-09-30 09:40
Thanks for your reply!
I do install Visual Studio 2015/2017!
1.I installed with  'npm install node-gyp ", is it right?
2. How to install winpty ?
any guide for this? thanks

**Comment by Tyriar** [comment] 2017-10-01 14:30
`npm install` is all you should need to do to build the demo.

**Comment by lonelywolf4git** [comment] 2017-10-07 07:00
I did execute `npm install` but get the same issue with [https://github.com/sourcelair/xterm.js/issues/562](url)

**Comment by Tyriar** [comment] 2017-10-10 14:59
#562 was caused by the terminal, have you tried using regular powershell or cmd?

**Comment by Tyriar** [comment] 2018-01-29 14:51
This works fine for me, closing

**Closed by Tyriar** 2018-01-29 14:51 UTC
Labels: needs more info
