### ISSUE TITLE
Random 1px white borders in Firefox in `xterm-text-layer` canvas

### ISSUE THREAD

**Issue by jankeromnes** [xtermjs/xterm.js#1974] opened 2019-03-21 16:40 UTC
## Details
- Browser and browser version: Firefox Nightly
- OS version: Mac OS
- xterm.js version: Latest

### Steps to reproduce

1. Visit https://xtermjs.org/ in Firefox
2. Open Devtools, set `document.body.style.backgroundColor = 'black'`
3. Resize the window to get the example xterm to resize

In some sizes, there is a random 1px white border (either top, bottom, left, right, or a combination of those). E.g.:

<img width="735" alt="Screenshot 2019-03-21 at 17 36 45" src="https://user-images.githubusercontent.com/599268/54768719-0e970500-4c00-11e9-95bd-a7e42040d518.png">

(bottom)

<img width="734" alt="Screenshot 2019-03-21 at 17 37 18" src="https://user-images.githubusercontent.com/599268/54768727-12c32280-4c00-11e9-967a-aa443297ba64.png">

(top)

This line looks like some off-by-one error. I also believe the error is only inside this `canvas`:

```html
<canvas class="xterm-text-layer" style="z-index: 0; width: 720px; height: 384px;" width="1440" height="768"></canvas>
```

(Deleting the others doesn't impact the white lines, while deleting this one removes all white lines.)

**Comment by Tyriar** [comment] 2019-03-23 16:15
Could not repro this on Firefox 63, 65 and 66 on Windows 10.

**Comment by Tyriar** [comment] 2019-03-23 16:18
I saw it once on macOS but not again, seems pretty hard to repro 🤔

**Comment by jankeromnes** [comment] 2019-03-27 15:58
It happens fairly consistently for me on https://gitpod.io (which uses xtermjs for its terminal) on Mac OS in Firefox Nightly.

Please let me know if I can do anything to help debug this.

**Comment by rhamilto** [comment] 2019-04-18 20:12
I'm seeing this issue and working around it with the following CSS:
```
.xterm .xterm-screen canvas {
  // fix bug where 1px white stripe appears atop terminal in Firefox
  border-right: 1px solid transparent;
}
```

**Comment by jankeromnes** [comment] 2019-05-22 08:03
Thanks for the tip @rhamilto! Unfortunately, playing with transparent borders on `.xterm-screen canvas` did not work around the issue in my Firefox Nightly:

<img width="928" alt="Screenshot 2019-05-22 at 10 00 52" src="https://user-images.githubusercontent.com/599268/58157439-96d56d00-7c78-11e9-96f5-ac2155e65ebf.png">

**Comment by lramos15** [comment] 2019-07-29 21:37
Unable to repro on Firefox nightly on MacOS.

**Comment by jankeromnes** [comment] 2019-07-30 06:54
FYI this bug still reproduces for me (Firefox Nightly on MacBook Pro):

https://youtu.be/minfGofKJ8c

**Comment by imdurgadas** [comment] 2020-08-06 05:15
Issue still happens, can we have a fix please.. This is  bad from User experience.

**Comment by jankeromnes** [comment] 2020-08-06 07:51
FYI, in Eclipse Theia and Gitpod.io we ended up using a CSS hack as workaround for this issue:

https://github.com/eclipse-theia/theia/issues/4665#issuecomment-494699663

https://github.com/eclipse-theia/theia/blob/8d8406d52b74b4fc03b4919a1299dc572b1e3bd5/packages/terminal/src/browser/style/terminal.css#L24-L27

**Comment by Tyriar** [comment] 2020-08-10 16:44
I'm good to accept a PR for the hack as long as the reason for it is called out in a comment. Since it needs the background color it will need to be set in JS instead of CSS.

**Comment by flippy84** [comment] 2020-11-09 00:59
Saw this bug with Firefox 82.0.2 and managed to reproduce it with the following code:

`
<!doctype html>
<html lang="en">
<head>
  <link rel="stylesheet" href="node_modules/xterm/css/xterm.css"/>
  <script src="dist/main.js"></script>
  <title>Terminal</title>

  <style type="text/css">
    body {
      margin: 0;
      padding: 0;
      background-color: black;
    }

    #terminal {
      width: 100vw;
      height: 100vh;
      box-sizing: border-box;
      padding: 4pt;
    }
  </style>
</head>
<body>
<div id="terminal"></div>
</body>
</html>
`

If the padding instead is changed to 4px instead of 4pt the border disappears. Easiest way I found to reproduce the issue was to switch back and forth between another tab.

**Comment by rivelbab** [comment] 2020-12-02 12:48
I changed the rendererType to dom to resolve this in firefox (linux OS).

**Comment by Tyriar** [comment] 2021-10-11 16:41
Closing as I can't reproduce so can't action. Open to PR to fix it if you can though.

**Closed by Tyriar** 2021-10-11 16:41 UTC
Labels: type/bug, browser/firefox, area/renderer, help wanted, good first issue, platform/macos
