### ISSUE TITLE
Error: Uncaught TypeError: Cannot set properties of undefined (setting 'innerText')

### ISSUE THREAD

**Issue by DavidSichau** [xtermjs/xterm.js#4282] opened 2022-12-01 16:04 UTC
We see errors in our telemetry in xterm:

```
Error: Uncaught TypeError: Cannot set properties of undefined (setting 'innerText')
```

## Details
![image](https://user-images.githubusercontent.com/1065395/205100652-de6a0eb7-523d-4a32-87b0-f6e9bbd3169a.png)
- xterm.js version: 5.0.0

### Steps to reproduce

We are not able to reproduce this in development.

In our production environment, we see this error around 30 times per hour when around 300 users are actively working.

**Comment by Tyriar** [comment] 2022-12-01 17:32
This is probably where it was happening:

https://github.com/Tyriar/xterm.js/blob/904ddffc8d370421783f0917797617bfce508854/src/browser/renderer/dom/DomRenderer.ts#L369
https://github.com/Tyriar/xterm.js/blob/904ddffc8d370421783f0917797617bfce508854/src/browser/renderer/dom/DomRenderer.ts#L357-L359

Which is now:

https://github.com/xtermjs/xterm.js/blob/4451369c664b8ba7a94a7902ca6023d6838feb25/src/browser/renderer/dom/DomRenderer.ts#L362
https://github.com/xtermjs/xterm.js/blob/4451369c664b8ba7a94a7902ca6023d6838feb25/src/browser/renderer/dom/DomRenderer.ts#L340-L349

So chances are this will now be complaining about `replaceChildren`.

**Comment by Tyriar** [comment] 2023-08-13 17:58
Duplicate of https://github.com/xtermjs/xterm.js/issues/4602

**Closed by Tyriar** 2023-08-13 17:58 UTC
Labels: type/bug
