### ISSUE TITLE
It will get a character "%" when terminal window is small

### ISSUE THREAD

**Issue by YikaJ** [xtermjs/xterm.js#2564] opened 2019-11-13 07:01 UTC
## Details
- Browser and browser version: Electron 4.1
- OS version: Mac 10.14.6
- xterm.js version: 3.14.5

### Steps to reproduce

I use node-pty with xterm.js, and the shell is zsh. (It's nice with the default bash.)

When the window is big enough, it looks well.

width: 1360px;
![image](https://user-images.githubusercontent.com/8725110/68739717-70d7c680-0624-11ea-98c8-06802cca4d0b.png)

But if I resize the window smaller, and the character "%" shows up.

width: 405px;
![image](https://user-images.githubusercontent.com/8725110/68739778-9b298400-0624-11ea-8c09-3edfd2dbe0ec.png)

Here are how I connect node-pty and xterm.js.

![image](https://user-images.githubusercontent.com/8725110/68740064-31f64080-0625-11ea-9116-452f086be641.png)

And here are the logs, but they look same.

Expected:
![image](https://user-images.githubusercontent.com/8725110/68740206-86012500-0625-11ea-84ba-52438fe40cc3.png)

Unexpected:
![image](https://user-images.githubusercontent.com/8725110/68740228-94e7d780-0625-11ea-8cbf-b3bdcf8bc459.png)

How to resolve this problem ? Thank your guys.

**Comment by Tyriar** [comment] 2019-11-15 04:20
It happens in VTE as well, looks like it's related to pty and terminal size being out of sync? https://github.com/zeit/hyper/issues/3586

@jerch thoughts? I had this reported to VS Code a few times as well.

**Comment by jerch** [comment] 2019-11-15 11:15
@Tyriar Imho thats a zsh specialty (never seen it in other shells) - whenever a line has no EOL before prompt zsh seems to mark it with '%'.

Question here is - what happened to the '\n' during resize? Beside a short prompt those lines are empty, why they are affected at all? This looks like it is oh-my-zsh driven. I'd search the culprit among their scripts, something does not deal with resizing that well and prolly swallowed the '\n'.

About resizing itself - yes we have a short time frame where things are out of sync. We cannot do much about it, also this applies only to data flowing in while resizing, other data should not be affected.

Summary: This is not an xterm.js issue, it will happen in other emulators as well. We might have unfortunate circumstances during resize that further provoke this, but cannot be fixed easily.

**Comment by Tyriar** [comment] 2019-11-15 18:01
> About resizing itself - yes we have a short time frame where things are out of sync. We cannot do much about it, also this applies only to data flowing in while resizing, other data should not be affected.

I was thinking about doing synchronous resizes for vscode a while ago, is this expected to fix the problem?

**Comment by jerch** [comment] 2019-11-15 20:35
@Tyriar Not completely fixing, but lowering, yes. There are still buffers involved, that are beyond any control with pty master side (all on slave side).

**Comment by Tyriar** [comment] 2019-11-17 20:13
@jerch should we close as designed? I think oh-my-zsh closed as not their problem.

**Comment by jerch** [comment] 2019-11-17 20:24
@Tyriar Yeah its currently as designed, unless you want to open that construction site in near future...

**Closed** 2019-11-17 20:28 UTC
Labels: needs more info
