### ISSUE TITLE
Solution for permanently fix Clipboard API issues without API fix and make XtermJS better

### ISSUE THREAD

**Issue by afi-dev** [xtermjs/xterm.js#4644] opened 2023-08-04 21:30 UTC
### Feelings exposed:

Destined for @Tyriar. 

You may be familiar with the recurring issues with **Non-functional copy-paste with canvas** on **Xterm.js** due to **browser security constraints** in [ClipboardAPI](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) exposed on many issues like this one [2478](https://github.com/xtermjs/xterm.js/issues/2478). I come to suggest you a better solution than the Canvas used by xtermjs which could make it better, because a lot of developper which use Xtermjs have a lot of difficulty to implement **clipbaordAPI** with xtermjs in security environement on web browser.

Currently, Xterm.js uses canvas to provide an integrated terminal experience. Unfortunately, we have a major problem with the copy and paste functionality of Xterm.js. Modern browsers impose increasingly strict security restrictions on clipboard access from JavaScript, which prevents copy and paste from working properly in the terminal because you have to capture copy/paste key events with JS. This limitation is a major drawback for all developers/users who rely on this functionality for efficient use of the terminal.

There are some people who cheat with crazy tricks with the Clipboard API but it's true that it's becoming a headache and very boring to have to tinker with things. I know you're very active and I've even seen that you're one of the main contributors to [htermjs](https://hterm.org/). In this sense I was able to test [htermjs](https://hterm.org/) and tweak tests with it and I am convinced that we could replace the canvas system of XtermJs and do as for [htermjs](https://hterm.org/), a system for displaying lines with x-rows. The only problem I've seen is that [htermjs](https://hterm.org/) doesn't handle the position of the terminal text cursor, but that's just because it's not finished. With a bit of work I'm sure we could finally implement native copy/paste support by replacing canvas.

I am aware, and all developers are aware of your [Copy/Paste xtermjs API](https://github.com/xtermjs/xterm.js/issues/2390) that you have implemented. The problem is that it's a shaky solution, and I believe Xtermjs should stop using memory-intensive <canvas> for the browser and instead focus on reverting to using divs for line management. This would address several issues, including performance problems that currently require WebGL fixes. Furthermore, it would resolve the drawback of the ClipboardAPI, as the terminal lines would be treated as HTML paragraphs by the browser, eliminating the need for integrating any API or JavaScript workaround. In my opinion, [htermjs](https://hterm.org/) is a good experiment as it addresses this problem.

I would appreciate your feedback on this matter, but I think it's time to abandon false solutions and prioritize native approaches integrated by web browsers.

Sincerely, Afi

### Problem:

Currently, Xterm.js uses canvas to provide an integrated terminal experience. Unfortunately, we have a major problem with the copy and paste functionality of Xterm.js. Modern browsers impose increasingly strict security restrictions on clipboard access from JavaScript, which prevents copy and paste from working properly in the terminal because you have to capture copy/paste key events with JS. This limitation is a major drawback for all developers/users who rely on this functionality for efficient use of the terminal.

### Solution:

Change/Rework the canvas rendering to a div rendering like htermJS.

## Improved Performance:

Using div elements with xterm.js can lead to significant performance improvements compared to canvas-based implementations. Div elements are more lightweight and have simpler rendering requirements like class, id, data, resulting in smoother and faster terminal interactions, especially on low-powered devices or in resource-constrained environments.

## Improved DOM Interactions and Events:
Div elements allow for better integration with other DOM elements and events, enabling seamless interactions with other components on the web page.

## Native Copy/Paste:
Unlike canvas-based implementations, div elements natively support copy and paste operations. Users can effortlessly select text within the terminal interface using their mouse or keyboard shortcuts and then copy it to the clipboard with the usual Ctrl+C (or Command+C on macOS) shortcut. Similarly, users can paste content from the clipboard into the terminal using Ctrl+V (or Command+V on macOS). This seamless integration enhances the user experience, making the terminal interface feel more familiar and intuitive. This does not require extensive tinkering with the Clipboard API.

## Native Styling:
With div-based rendering, you can define various CSS classes to customize the appearance of the terminal elements, such as the text color, background color, font, padding, and borders. This provides greater flexibility in styling and makes it easier to match the terminal's appearance to the overall design. The best part is that it doesn't require any JavaScript.

**Comment by Tyriar** [comment] 2023-08-04 22:02
If you don't load the canvas or webgl addons, the terminal does use divs/html elements to render the text. We do however intercept all mouse down events and display our own selection because:

- We want full control of the renderer so there are no gaps between the lines, so the selection expands into the whitespace on the right.
- Even though our dom renderer is using divs, we virtualize the viewport and only the visible rows are rendered. This means it would not be possible to select more than the viewport using native browser selection. We could of course revert to how xterm.js used to do it years and years ago, but then we would be going back to the days [where is was 5 to 45 times slower than it is currently](https://code.visualstudio.com/blogs/2017/10/03/terminal-renderer), scaling based on scrollback length (back then, the numbers would be different now).
- We need to overwrite what is copied because some of it needs fine grained control (eg. '&nbsp;' -> ' ').
- The more code we share between all renderers the better, selection logic (not rendering) is all separated from the renderer and runs the same regardless of the renderer used.

I know the documentation is a bit lacking, but the approach we take right now is to give the embedder full control over everything by hooking up the handlers manually. While also providing things like bracketed paste mode without you needing to worry about it. The clipboard limitations are certainly annoying, but moving to the div-based rendering you're suggesting isn't a real solution imo and goes against a lot of what the library is trying to accomplish.

**Comment by jerch** [comment] 2023-08-06 16:03
> Using div elements with xterm.js can lead to significant performance improvements compared to canvas-based implementations. Div elements are more lightweight and have simpler rendering requirements like class, id, data, resulting in smoother and faster terminal interactions, especially on low-powered devices or in resource-constrained environments.

Thats in general not true and in fact the opposite is the case - div rendering/layouting is much more expensive, esp. if you want to preserve the scrollback as life content in the DOM. Thats the reason for the different renderer implementations, which gave xtermjs significant speedup, and if they were not buggy on certain machines we would have dropped the DOM renderer long ago.
To make it blunt - you long writing above is based on the false claim, that "div elements are more lightweight and have simpler rendering requirements" - nope, they are much more heavy on perf side of things.

**Comment by bogdanv-ntnu** [comment] 2023-08-11 10:22
Is there a way to fix [this issue](https://github.com/webmin/authentic-theme/discussions/1667)?

**Comment by Tyriar** [comment] 2023-08-11 10:52
@bogdanv-ntnu I'm guessing that a rendering problem, not to do with the clipboard. It could also be an issue in webmin, like they may not be on the latest.

**Comment by Tyriar** [comment] 2023-08-11 10:55
Closing as it's by design we're not using standard DOM as suggested above.

TLDR:

- We're not rendering as a plain DOM document for very good reasons, in fact xterm.js used to do this back when it was incredibly slow.
- The Clipboard API and it's security restraints are what you should be using, there's a reason they exist.
- I agree our documentation is poor, that's tracked in https://github.com/xtermjs/xterm.js/issues/2478

**Closed by Tyriar** 2023-08-11 10:55 UTC
