### ISSUE TITLE
`;` inside the URL breaks the OSC hyperlink

### ISSUE THREAD

**Issue by schaffino** [xtermjs/xterm.js#4944] opened 2024-01-22 16:16 UTC
Tried this in both VSCode and Jupyterlab. It seems the OSC hyperlink integration doesn't work properly when the linked URL contains a ';' 

The following submitted to terminator terminal emulator results in a link directing me to https://www.example.com/query;arg=1;arg=2;arg=3

printf '\e]8;;https://www.example.com/query;arg=1;arg=2;arg=3\e\\This is a link\e]8;;\e\\\n'  

Running the same in jupyter or VSCode, I end up being redirected to https://www.example.com/query, with the arguments truncated

## Details
- Browser and browser version: Any
- OS version:  Any
- xterm.js version: Any supporting OSC hyperlinks

### Steps to reproduce

1.  Output a valid OSC hyperlink in tooling using xterm.js (See printf statement above)
2.  Observe the link is truncated

**Comment by Tyriar** [comment] 2024-01-30 18:09
Before fixing this we should verify that `;` is expected to be supported when not URL encoded as `%3B`

**Comment by jerch** [comment] 2024-01-30 22:44
@Tyriar https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#encodings states, that additional uri params may not contain `:` or `;` due to its ambiguity with the sequence syntax. Thus I'd say this works as intended by the spec.

**Comment by Tyriar** [comment] 2024-01-30 23:07
Cool, I suspected that might be the case. Closing as designed then

**Comment by schaffino** [comment] 2024-02-02 13:42
@Tyriar @jerch 
The parameters its referencing in the doc above is referring to the optional parameter argument of the OSC-8 hyperlink, not query parameters in the URI. It states that only id is specifically defined in the spec for this argument. My reading is that the URI can still be any string in the range  32–126. Given most other terminal emulators support this i believe this is still a bug.

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence


It explicitly says the URI can be anything in the 32-126 when stating it cannot contain : or ;, which is a seperate argument to the URI. It states the URI can be anything in the ascii range.  Without support for ; there are plenty of valid URI's that cannot be linked

**Comment by Tyriar** [comment] 2024-02-02 17:37
@schaffino makes sense, thanks for the follow up. I read the "additional parameters" part wrong.

**Comment by jerch** [comment] 2024-02-02 21:35
Eww, seems I also misread that.

**Comment by josiahhudson** [comment] 2024-03-15 21:45
Attempted a fix here: https://github.com/xtermjs/xterm.js/pull/5003

**Closed** 2024-04-22 08:41 UTC
Labels: type/bug, help wanted, good first issue
