### ISSUE TITLE
[fit addon] term.renderer.dimensions properties are null

### ISSUE THREAD

**Issue by ficristo** [xtermjs/xterm.js#1213] opened 2018-01-17 09:39 UTC
I'm trying to update my [extension](https://github.com/ficristo/brackets-terminal-x) with xterm 3.
When I call term.fit() it enters in an infinite loop. That is because `term.renderer.dimensions` properties are all null which leads to cols and rows to be Infinity.
And here will enter in an infinite loop https://github.com/xtermjs/xterm.js/blob/5888cd7938fa00d3756287dfcfd23f0ea0716d96/src/Buffer.ts#L129

Probably I still miss some step to upgrade. Meanwhile do you have an idea why `term.renderer.dimensions` properties can be all null?
I would be nice to have some guards to prevent the infinite loop.

## Details
- Browser and browser version: Brackets extension (Chrome 49 with CEF)
- OS version: Windows 10
- xterm.js version: 3.0.2

### Steps to reproduce

1. Call `term.fit()`

**Comment by mofux** [comment] 2018-01-17 09:59
Did you call `term.open(element)` prior calling `term.fit()`? You have to make sure that the terminal element is attached to the DOM (which is after you have called term.open(element)) before you can use `term.fit()`. Also make sure that the element you are passing to `term.open` is already attached to the DOM. Anyway, we should detect and handle this case somehow. See #1158 for more details.

**Comment by ficristo** [comment] 2018-01-17 11:12
I was creating an element, calling `term.open()` passing it and then adding the element in the page.
I changed to code to call `term.open()` after adding the element in the page without success.
In both cases the element is added in a panel which is initially hidden.
Do the parent needs to be visible in the page? If I make the panel visible and then call `term.fit()` shouldn't it work regardless if previously the parent was hidden?

**Comment by blink1073** [comment] 2018-01-17 11:15
@ficristo, I had the same issue.  The element must be visible because the renderer is taking measurements on `open()`, e.g. [here](https://github.com/xtermjs/xterm.js/blob/5888cd7938fa00d3756287dfcfd23f0ea0716d96/src/Terminal.ts#L663).

**Comment by mofux** [comment] 2018-01-17 11:16
Yes the terminal has to be visible when calling term.open, because that is the moment where the renderer creates a dummy span element to measure the size of a character. If the parent element is hidden (e.g. `display: none`) it will measure incorrect sizes.

**Comment by ficristo** [comment] 2018-01-17 11:26
For now I found that calling `term.charMeasure.measure(term.options);` before `term.fit()` works as workaround. Is it safe to call it?

**Comment by Tyriar** [comment] 2018-01-18 00:00
Is there any reason why you don't call fit when you're sure the element is visible? Why do you want to initialize the visible parts when they're not being used yet?

**Comment by blink1073** [comment] 2018-01-18 00:40
The problem for me wasn't the call to fit, but the call to open which we had previously done before the host element was visible.  Now that a measurement is part of the call to open, we have to defer it until the element is both added to the DOM and visible.

**Comment by ficristo** [comment] 2018-01-18 09:08
@Tyriar I'm calling fit when the element is visible. But now I also need to make sure to call `open` when the element is visible otherwise successive call to `fit` will not work.

**Comment by Tyriar** [comment] 2018-01-18 16:03
Ah ok, I'll close this off then as the root cause seems to be open when it's not visible again. This was added to the API docs I think after @blink1073's report.

**Closed by Tyriar** 2018-01-18 16:03 UTC
