### ISSUE TITLE
Calling `XTerm.fit` with a non-visable terminal results in thrown error

### ISSUE THREAD

**Issue by Nokel81** [xtermjs/xterm.js#3118] opened 2020-09-30 19:53 UTC
## Details
- Electron: 9.1.2
- Chrome: 83.0.4103.122
- OS version: macos 10.15
- xterm.js version: 4.9.0

### Steps to reproduce

1. Have the terminal not being rendered
2. Using the `FitAddon` call `fit()`
3. Observe the `This API only accepts integers` error.

Seems like this has regressed from #525 but that was over 3 years ago (with at least one major refactor) so I couldn't find when this happened.

**Comment by Tyriar** [comment] 2020-11-04 22:46
The API is a little more strict now and will throw invalid values instead of silently failing.

This is kind of by design, but we could throw a more descriptive error instead of passing invalid values to `Terminal.resize`.

**Comment by hantatsang** [comment] 2021-02-15 15:04
@Nokel81 what's the exact code to replicate this issue?

**Comment by jocelc** [comment] 2021-06-19 08:19
I had experienced this problem and resolved it with checking xterm component exist or not before using the FitAddon call fit() @Nokel81

**Comment by Tyriar** [comment] 2021-07-06 21:37
The key to repro here I think is:

> Have the terminal not being rendered

So don't call `open` on the terminal object to attach it to the DOM.

**Comment by Nokel81** [comment] 2021-07-06 23:40
Is that not how you are supposed to attach it to the DOM?

**Comment by Tyriar** [comment] 2021-07-07 10:09
It is, but we should probably just do nothing when fit is called if it's hot attached. Either before open is called or if open is called but the element it's attached to is not in the document.

**Comment by panick-carousel** [comment] 2021-07-19 05:01
Given the difficulty in determining if the terminal is visible or not before deciding to call fitAddon.fit(), and given that technically speaking, if the terminal isn't visible then doing nothing has actually made it fit 🤷 doing nothing would be much more polite.

We hit this issue due to hot reloading during debugging swapping out components sometimes.

**Comment by enncy** [comment] 2022-03-07 13:44
I thank that the best way to use `FitAddon` : 
```js
const dimensions = fitAddon.proposeDimensions();
if (dimensions.cols && dimensions.rows) {
    this.resize(dimensions.cols, dimensions.rows);
}
```

**Comment by mankeheaven** [comment] 2022-05-16 05:04
thank you @enncy, it's ok in my electron enviroment.
maybe fitAddon can provide a fitResize function 
```
FitAddon.prototype.fitResize = () => {
  const dimensions = this.proposeDimensions();
  if (dimensions?.cols && dimensions?.rows) {
      this.xterm.resize(dimensions.cols, dimensions.rows);
  }
}
```

**Comment by jerch** [comment] 2022-06-30 21:43
@Tyriar It seems the returned geometry from `proposeDimensions` might end up as `{cols: NaN, rows: NaN}`, where the follow-up `resize` call will fail upon. We should at least handle that more friendly by testing for NaN as a last check and returning `undefined` instead. This would be a partial fix to the issues described here. (We still cannot do much about a non-attached terminal.)

(I am not quite sure, why NaN still can occur, would have thought that the guards in `proposeDimensions` are sufficient to catch all edge cases...)

**Comment by jerch** [comment] 2022-06-30 22:19
@Tyriar Imho this got fixed in https://github.com/xtermjs/xterm.js/commit/5c9adeef930b969bc822470b504ae690d82dd05e by returning early for NaN.

**Closed** 2022-07-01 17:04 UTC
Labels: type/bug, help wanted, good first issue
