### ISSUE TITLE
WebGL rendering is broken on Safari Preview

### ISSUE THREAD

**Issue by prusnak** [xtermjs/xterm.js#3357] opened 2021-06-02 08:45 UTC
## Details

- Browser and browser version: Safari 14.1
- OS version: macOS 11.3 (Apple Silicon)
- xterm.js version: 4.11.0 (gotty 1.3.0)

### Steps to reproduce

1. install xterm.js with webgl addon
2. open the page in Safari
3. observe missing letters, just background colors can be seen
3. Chrome and Firefox work fine

**Comment by jerch** [comment] 2021-06-02 09:10
@prusnak Do you get any output at all? I think you should not - as far as I know Safari does not implement Webgl2 at all. Or did they change that recently?

**Comment by Tyriar** [comment] 2021-06-02 10:15
I think you may need to switch in webgl2 via an experimental feature in Safari. I'm not sure if that changes on M1.

**Comment by prusnak** [comment] 2021-06-02 10:21
> I think you may need to switch in webgl2 via an experimental feature in Safari. I'm not sure if that changes on M1.

Ah, it was actually the opposite :-) 

I had WebGL 2.0 enabled in experimental settings and turning it off fixed the issue for me.

Feel free to close the issue if you want to.

**Comment by Tyriar** [comment] 2021-06-02 12:10
Ah ok, I guess that's why it's experimental then 😄. If it's off, loading the addon will throw and it will revert back to the DOM renderer.

**Comment by Tyriar** [comment] 2021-08-09 15:44
We're seeing this on ipad and the safari preview still

**Comment by Tyriar** [comment] 2021-08-09 17:18
@meganrogge and I looked into this just now, here's what we found:

- The issue is just with rendering of text, not backgrounds (see the green above which is webgl powered)
- The uploaded texture appears correct when getImageData is used and inspected on the browser side, but using the texture in the fragment shader doesn't seem to work
- Using `vec4(1.,0.,0.,1.)` here shows red where the glyphs should show as expected: https://github.com/xtermjs/xterm.js/blob/522c8bf3afcc296f7586c21b097025fe3626dc32/addons/xterm-addon-webgl/src/GlyphRenderer.ts#L69
- Also using `vec4(v_texcoord,0.,1.)` looks as expected (differing shades of red)

**Comment by only-cliches** [comment] 2021-09-22 23:43
This is now happening for release versions of Safari.

Is there someway the WebGL renderer can be disabled for Safari until there's a fix?

**Comment by shohey1226** [comment] 2021-09-23 04:22
I’ve encountered this in iPadOS15. Once WebGL2.0 is disabled, it start to work again.. 

![IMG_0578](https://user-images.githubusercontent.com/1880965/134453535-1c86efca-ce9b-4d1c-ac18-c12088b8fa18.jpeg)

**Comment by meganrogge** [comment] 2021-09-27 15:29
for safari, we don't enable webgl https://github.com/microsoft/vscode/blob/aa93bc5e86dc929f07c5bfa51771c43664d15bdd/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1589

**Comment by Tyriar** [comment] 2021-10-12 12:53
@bushev did you mean to paste in a different issue?

FWIW the PR linked above will now cause the webgl addon to throw when you try to activate it on Safari as a temporary workaround.

**Comment by bushev** [comment] 2021-10-14 19:37
Got it, the issue I've pasted just looks similar to this rendering issue, since some characters are missing in the console. But disabling od WebGL 2.0 doesn't help to solve #3357.

**Comment by litherum** [comment] 2021-12-14 05:30
The check in https://github.com/xtermjs/xterm.js/blob/master/src/common/Platform.ts#L21:

```
export const isSafari = /^((?!chrome|android).)*safari/i.test(userAgent);
```

doesn't seem to catch WKWebView, which is the browser engine powering Safari. Safari's user agent string (on an iPad) is:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
```

Whereas WKWebView's user agent string (on an iPad) is:
```
Mozilla/5.0 (iPad; CPU OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

This is causing the demo on https://xtermjs.org to not show any content in WKWebView. I've reported this at https://github.com/xtermjs/xterm.js/issues/3575 but I'm also mentioning it here in case it's relevant.

**Comment by jerch** [comment] 2022-03-31 12:50
> ... while it ran out of memory after adding the 8th parrot ...

@daonb Any pointers/traceback where things went overboard with 8th parrot?

**Comment by Tyriar** [comment] 2022-03-31 14:24
That's exciting if this will be fixed in the upcoming Safari!

**Comment by daonb** [comment] 2022-03-31 14:33
> @daonb Any pointers/traceback where things went overboard with 8th parrot?

I suspect Safari ran out of canvas memory as it always does when I keep opening panes. All the parrots freeze and I there's no more canvas output. I added an `onContextLoss` handler with a console log but got nothing. I also tried without the WebGL addon and got the same frozen parrots so it's probably an out of memory issue.

**Comment by Tyriar** [comment] 2022-03-31 14:36
I'm not sure I've seen the browser refusing to hand out GPU memory but that would be my guess as well.

**Comment by Tyriar** [comment] 2022-03-31 14:53
@jerch pretty sure they're each individual instances

**Comment by daonb** [comment] 2022-03-31 17:22
> Are those panes full terminal instances (no clue how you do the multiplexing)?

Yes they are - whenever the user splits a terminal he gets a new terminal and a new WebRTC data channel. I should probably run a more focused benchmark - in this one each parrot comes from `curl parrot.live` so it also loads the network. I'd love to hear any suggestions how to better test performance and the limitiations.

**Comment by r10r** [comment] 2022-05-13 09:42
As stated in https://github.com/xtermjs/xterm.js/issues/3357#issuecomment-1084531272  this is fixed in the current safari version. I just want to confirm that it works fine for me in *Safari Version 15.4 (17613.1.17.1.13)*   with **WebGL 2.0** enabled.

**Comment by Tyriar** [comment] 2022-05-13 12:10
Also works for me on 15.4 after removing this:

https://github.com/xtermjs/xterm.js/blob/d29388394c60cef40dc0aa4aece9aad94ac46945/addons/xterm-addon-webgl/src/WebglAddon.ts#L28-L30

Let's keep the workaround there for a while until 15.4+ is more widely spread https://caniuse.com/usage-table

**Comment by aeriksson** [comment] 2022-10-21 07:06
> Let's keep the workaround there for a while until 15.4+ is more widely spread https://caniuse.com/usage-table

Safari tells you which version it's running via `navigator.appVersion` (e.g. `navigator.appVersion.match(/Version\/([0-9.]+).*Safari/)[1] => "15.6"`). A much better workaround would be to only disable the WebGL addon on versions lower than 15.4.

**Closed** 2022-11-08 20:30 UTC
Labels: type/bug, browser/safari
