### ISSUE TITLE
The scroll bar goes out of sync if the terminal is detached and reattached to the DOM

### ISSUE THREAD

**Issue by roguexiaohuihui** [xtermjs/xterm.js#2647] opened 2019-12-25 07:49 UTC
## Details
- Browser and browser version:  electron 1.6.6
- OS version:  win10
- xterm.js version:  4.0

### Steps to reproduce
Links to specific questions are as follows:
https://github.com/xtermjs/xterm.js/issues/291

Our project used to use xterm 2.5 version，then trigger scroll event manually so that the viewport's scroll area is synced.

`this._xterm.emit('scroll', this._xterm.ydisp);`

Now after upgrading to xterm4.0, we also want to manually trigger the scroll event to keep the scroll bar synchronized. The code is as follows:

`this._xterm.scrollLines(this._xterm.buffer.viewportY);`

But neither scrollLines nor scrololine solves the scrollbar synchronization problem.

**Comment by roguexiaohuihui** [comment] 2019-12-26 03:09
`  public scrollLines(disp: number, suppressScrollEvent?: boolean): void {
    if (disp < 0) {
      if (this.buffer.ydisp === 0) {
        return;
      }
      this._userScrolling = true;
    } else if (disp + this.buffer.ydisp >= this.buffer.ybase) {
      this._userScrolling = false;
    }

    const oldYdisp = this.buffer.ydisp;
    this.buffer.ydisp = Math.max(Math.min(this.buffer.ydisp + disp, this.buffer.ybase), 0);

    // No change occurred, don't trigger scroll/refresh
    if (oldYdisp === this.buffer.ydisp) {
      return;
    }

    if (!suppressScrollEvent) {
      this._onScroll.fire(this.buffer.ydisp);
    }

    this.refresh(0, this.rows - 1);
  }`

I looked at the source code implementation, and then used the following code in the project to solve:

`this._xterm._core._onScroll.fire(this._xterm.buffer.viewportY);`

**Comment by Tyriar** [comment] 2019-12-27 16:13
Duplicate of https://github.com/xtermjs/xterm.js/issues/291

VS Code uses the same workaround:

https://github.com/microsoft/vscode/blob/511a6242328d844ab826332bc057d53a35179844/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L908-L914

**Closed by Tyriar** 2019-12-27 16:13 UTC
