### ISSUE TITLE
no 'dist' build in releases ?

### ISSUE THREAD

**Issue by flumm** [xtermjs/xterm.js#1201] opened 2018-01-08 10:24 UTC
up to 2.9.2 the release tags included a 'dist' directory with the built package, ready for consumption

since 3.0.0 there is no 'dist' directory anymore, is this by design or accident?

self building would be very hard for us (proxmox) since on debian (which we use as base) neither npm nor gulp is packaged, and it would mean we would rely on non-debian repos for this (or a not very nice build-workflow)

  edit:

afaics, the dist/ is in the .gitignore (from the v3 branch) with a comment that this can be removed when merging v3 into master, but this did not happen, so i hope this was just a mistake

**Comment by Tyriar** [comment] 2018-01-08 18:28
It's probably a good idea to keep shipping this, but we should still keep it in the `.gitignore`. Thoughts @parisk?

**Comment by FGasper** [comment] 2018-01-08 20:34
In the meantime, is there a way to build the `dist` directory as before? `build` doesn’t include AMD loaders, which we use extensively in our application.

**Comment by Tyriar** [comment] 2018-01-09 00:00
Looks like the build task might have been removed to build `dist`. To use xterm.js do you install it from npm and then link to the files in `node_modules/xterm/dist/` from html?

**Comment by FGasper** [comment] 2018-01-09 01:05
Previously we just packaged up `dist/` into an RPM.

**Comment by blink1073** [comment] 2018-01-09 11:30
FWIW @cancan101 has found a way for us to continue pulling xterm in using bower in Jupyter Notebook: https://github.com/jupyter/notebook/pull/3189

**Comment by flumm** [comment] 2018-01-09 13:48
@Tyriar we use the git as a submodule for our own package and use the dist directory direclty in our build
as we cannot really use npm (see my comment about debian)

**Comment by parisk** [comment] 2018-01-09 15:20
OK, this was not by any means intentional 😅 . Will take a look.

**Comment by Tyriar** [comment] 2018-01-09 16:27
@parisk I was looking at the old issues as the decisions are a little hazzy for me and the plan was to continue shipping `dist/` after removing bower support. Just got lost in the noise of the webpack build I guess.

**Comment by parisk** [comment] 2018-01-10 09:29
@Tyriar you are right. I am trying to understand why this happened at all tbh. Seems like `dist` files are supposed to be included in the released, based on [`package.json` on `release/3.0`](https://github.com/xtermjs/xterm.js/blob/release/3.0/package.json#L19-L22):

https://github.com/xtermjs/xterm.js/blob/45ed27d329f625daf44513f112d5a2e1aa1e0ca8/package.json#L19-L22

**Comment by blink1073** [comment] 2018-01-10 09:41
Perhaps the issue is the git release not containing the dist files, as in they used to be checked in to the repo?

**Comment by blink1073** [comment] 2018-01-10 09:42
@parisk from my local test the dist files are included when installing from npm.

**Comment by flumm** [comment] 2018-01-10 09:47
@blink1073 @parisk @Tyriar just for clarity: i do not talk about npm releases (as i already explained we cannot use npm) but about the release tags in git (as we use this for our packaging)

afaics, during the development of the v3 branch, the dist directory was included in the .gitignore, so that
building there does not pollute the git repository with a comment that this can be removed when merging. a possible solution would be to manually add those files in the release script and leave it in the gitignore

**Closed** 2018-01-10 10:00 UTC

**Comment by flumm** [comment] 2018-01-10 10:04
@parisk is it really not possible to include the dist as a build artifact on git like you described in #406 ? if not, that means that for the foreseeable future we will not be able to update to a newer xtermjs release than 2.9.2 since neither npm nor yarn is available on debian 9 (adding external repositories in the build step is no really feasible for us).

**Comment by blink1073** [comment] 2018-01-10 10:15
@flumm, why not pull the package from npm.org instead of github?

```
$ npm view xterm dist.tarball
https://registry.npmjs.org/xterm/-/xterm-3.0.1.tgz
```

**Comment by parisk** [comment] 2018-01-10 10:16
@flumm no, we do not have any intentions to maintain distribution files in the repository, as we believe it's a bad practice.

You can find more information about this decision on the initial issue and PR:

- https://github.com/xtermjs/xterm.js/issues/406
- https://github.com/xtermjs/xterm.js/pull/882

**Comment by flumm** [comment] 2018-01-10 10:22
@blink1073 yes that seems to work :) thanks

@parisk yeah, in general i agree with you, but sadly with npm in combination with debian it is not easy to integrate stuff where the you can only build with npm/yarn/etc.
i simply missed the whole issue because i integrated xterm.js in proxmox well after those decisions were made

**Comment by parisk** [comment] 2018-01-10 10:25
@flumm I see your use case. You can give a try at Docker for your needs (if it's applicable to you). You can use the [node image](https://hub.docker.com/_/node/) to build your project.

Or you can just use the npm tarballs 😄.

All the best!

**Comment by FGasper** [comment] 2018-01-10 13:58
@parisk There is still no AMD loader anymore in the npm tarball’s `addons/fit/fit.js`. Can this be fixed?

**Comment by cancan101** [comment] 2018-01-10 14:29
What about just using nvm to install npm?

**Comment by Greenek** [comment] 2018-01-13 00:59
Feel free to use `bower install --save xterm.js-next`. It's [my fork](https://github.com/Greenek/bower-xterm.js) with created for personal use, but I try to keep it updated.

**Comment by fake-name** [comment] 2021-03-26 21:43
Wait, so you have to have npm and/or yarn installed just to get 2 files?

This is spectacularly ridiculous.  I'm working on  a project that doesn't use node *at all*, so I don't have any of the tooling. It does have a *clientside* web component, so I'd like to use xtermjs. However, apparently you can't actually *get* xtermjs.

People who don't use node exist. Requiring it just to get the distribution js files for serving is insane.

**Comment by raquelhortab** [comment] 2021-05-10 13:43
I completely agree with @fake-name. It is quite annoying having to clone and build the project just to get the distribution .js and .css. I've already cloned and build the project but still cannot find the files, should there be a dist or build folder somewhere? Can anyone explain how should I generate those files?

**Comment by Tyriar** [comment] 2021-05-10 13:53
@raquelhortab I think you're talking about something different, @fake-name wants the files without using node, which is available for example on https://www.jsdelivr.com/package/npm/xterm. I'm not entirely sure what you're after, perhaps you're missing running `yarn package` which generates the `lib` folder that is pointed to from `main` in package.json.

Regardless, both of these topics are unrelated to this original issue, feel free to create a new one to discuss but going to lock this as it's old and already resolved.
