### ISSUE TITLE
Copy is not working in safari after the implementation of new selection library

### ISSUE THREAD

**Issue by ManojkumarV** [xtermjs/xterm.js#815] opened 2017-07-24 07:15 UTC
Cmd+C is uses to copy the selected text in mac machines. But it is not working in safari browser after migrated to version 2.8.1. Cmd+V is working properly buy copy is not working.

**Comment by parisk** [comment] 2017-07-24 08:50
@ManojkumarV did you try this on the demo page or in another app?

Cmd + C and Cmd + V seems to be working on Safari for me (latest macOS) in the demo.

**Comment by ManojkumarV** [comment] 2017-07-24 11:00
@parisk I tried both demo and sourcelair in my safari browser, but copy is not working for cmd+c. Also copy paste seems to be working in some of the macOS machines. But it is not working in most of the machines. 
For example it is working in version 10.1.1 but it is not working in 10.1.2, 9.1. etc.

Can u please check with any other machine.

Thanks.

**Comment by parisk** [comment] 2017-07-24 11:09
@ManojkumarV, thanks for the details. I was able to reproduce this on macOS 10.11.5, Safari 9.1.1. Marking this as a bug.

**Comment by Tyriar** [comment] 2018-06-03 07:43
Works in latest for me

**Closed by Tyriar** 2018-06-03 07:43 UTC
Labels: area/clipboard, browser/safari, type/bug
