### ISSUE TITLE
SearchAddon need to support all highlighting

### ISSUE THREAD

**Issue by roguexiaohuihui** [xtermjs/xterm.js#2742] opened 2020-02-28 08:55 UTC
Now the SearchAddon plug-in can only search one by one using the findNext feature.

Can you highlight all the results at once, in different colors, and then trigger findNext to a search result and scroll to the corresponding location?

similar to the vscode search function.

**Comment by Tyriar** [comment] 2020-02-28 15:05
duplicate of https://github.com/xtermjs/xterm.js/issues/1653

**Closed by Tyriar** 2020-02-28 15:05 UTC
