### ISSUE TITLE
Terminal random missing first character because parsing data " $[K[1C" [[13,36,27,91,75,27,91,49,67]]

### ISSUE THREAD

**Issue by quyenlv-unicloud** [xtermjs/xterm.js#4600] opened 2023-07-19 02:59 UTC
## Details
- Browser and browser version: vscode 1.80.1
- OS version: Windows 11 10.0.22631
- xterm.js version: 5.3.0-beta.3

### Steps to reproduce

1. type `gitk --all` in terminal
2. it will random sometime missing first character -> `itk --all`
3. check terminal trace log showing `parsing data " $�[K�[1C" [[13,36,27,91,75,27,91,49,67]]`

```
2023-07-13 15:07:52.341 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:07:52.341 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:07:52.354 [trace] terminalMultiLineLinkDetector#detect text ["$"]
2023-07-13 15:07:52.354 [trace] terminalLocalLinkDetector#detect text ["$"]
2023-07-13 15:07:52.355 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:07:53.113 [debug] sending data "g" [[103]]
2023-07-13 15:07:53.129 [debug] parsing data "
$�[K�[1C" [[13,36,27,91,75,27,91,49,67]]
2023-07-13 15:07:53.187 [debug] sending data "i" [[105]]
2023-07-13 15:07:53.208 [debug] parsing data "i" [[105]]
2023-07-13 15:07:53.297 [debug] sending data "t" [[116]]
2023-07-13 15:07:53.315 [debug] parsing data "t" [[116]]
2023-07-13 15:07:53.392 [debug] sending data "k" [[107]]
2023-07-13 15:07:53.423 [debug] parsing data "k" [[107]]
2023-07-13 15:07:54.395 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:07:54.395 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:07:54.395 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:07:54.546 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:07:54.546 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:57.693 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:57.694 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:57.694 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:58.312 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.312 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.312 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:58.313 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:58.432 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.432 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:58.433 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:58.433 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
2023-07-13 15:09:58.472 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:58.472 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:58.473 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:59.339 [trace] terminalMultiLineLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:59.339 [trace] terminalLocalLinkDetector#detect text ["$ itk"]
2023-07-13 15:09:59.340 [trace] terminalLocalLinkDetector#detect parsedLinks [[]]
2023-07-13 15:09:59.353 [trace] terminalMultiLineLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect text ["REMOVED_INFO"]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect parsedLinks [[{"path":{"index":30,"text":"REMOVED_INFO"}}]]
2023-07-13 15:09:59.353 [trace] terminalLocalLinkDetector#detect linkCandidates [["REMOVED_INFO"]]
```

**Comment by jerch** [comment] 2023-07-19 09:23
Well, the sequence your are retrieving:

```
     [13,   36,  27,91,75,  27,91,49,67]
-->  '\r'   '$'  '\x1b[K'  '\x1b[1C'
-->   CR     $   EL0       CUF1
```
means:
- CR: move cursor to left-most cell
- $: print '$' + advance cursor by 1 to the right
- EL0: delete line content from cursor to the right
- CUF1: advance cursor by 1 to the right

Thats what xtermjs was instructed to do, so yeah - if the 'g' was printed before on the same row, it will get erased by that.

Question is - what generates and sends these row erase sequences? Since it contains a '$' to be printed, it looks like an issue with your shell setup ($ is often part of shell prompts). Since you are on windows, it could also be caused by conpty doing weird screen/row refreshs.

This does not look like an xtermjs bug to me, thus I gonna close the issue. Feel free to reopen, if you think otherwise.

**Closed by jerch** 2023-07-19 09:23 UTC

**Comment by quyenlv-unicloud** [comment] 2023-07-19 09:39
@jerch 

Hi, thank for explain, but is this log ok?
```
2023-07-13 15:07:53.113 [debug] sending data "g" [[103]]
2023-07-13 15:07:53.129 [debug] parsing data "
$�[K�[1C" [[13,36,27,91,75,27,91,49,67]]
2023-07-13 15:07:53.187 [debug] sending data "i" [[105]]
2023-07-13 15:07:53.208 [debug] parsing data "i" [[105]]
2023-07-13 15:07:53.297 [debug] sending data "t" [[116]]
2023-07-13 15:07:53.315 [debug] parsing data "t" [[116]]
2023-07-13 15:07:53.392 [debug] sending data "k" [[107]]
2023-07-13 15:07:53.423 [debug] parsing data "k" [[107]]
```

You can see `sending data "g"` it mean xterm got correct input.
But next line, `parsing data $�[K�[1C" [[13,36,27,91,75,27,91,49,67]]`

Because got correct input but later parsing wrong data, so I think xterm converted or do something make input become wrong?

**Comment by jerch** [comment] 2023-07-19 12:10
No the log does not look ok to me - the 'g' seems never to get sent back (there is not 'g' in the parsing entries). But thats happening outside of xtermjs - some logic seems to swallow the 'g' input here.
