### ISSUE TITLE
Last char on the line not visible (wrapped) for some fonts

### ISSUE THREAD

**Issue by texcoffier** [xtermjs/xterm.js#4601] opened 2023-07-20 08:50 UTC
## Details
- Browser and browser version: FireFox 115.0.1 (snap version)
- OS version: Ubuntu 22.04.2 LTS
- xterm.js version: 5.2.1

### Steps to reproduce
1. Display 80 characters on a line
2. Try some options.fontSize value until the last character disappear (wrapped).
    Size 21 or 24 in my case (may depends on installed fonts so difficult to reproduce).

If the cursor is moved on the hidden last char, it also disappear.

### Fix
The line element inline style is in my case:
```css
   {
     width: 812px;
     height: 21.3333px;
     line-height: 21.3333px;
     overflow: hidden;
   }
```
Two ways to fix:
1. Increase the width by 1 pixel (not very nice)
2. Add  `white-space: nowrap` (it is a more resilient fix)

**Comment by Tyriar** [comment] 2023-07-27 19:58
I can reproduce:
<img width="1390" alt="Screenshot 2023-07-27 at 12 55 41 pm" src="https://github.com/xtermjs/xterm.js/assets/2193314/7dc3a6d7-a9c7-4c20-b784-f83de471d2f1">

We are reworking the DOM renderer in https://github.com/xtermjs/xterm.js/pull/4605 and it looks like it still happens there.

**Comment by jerch** [comment] 2023-07-27 20:19
Hmm, my best guess here - the rounding of the single cell width adds to much leading to an overflow of the row width in the end. Not sure yet about the proper fix, depends alot how big the offset `cellWidth * cols > rowWidth` might get. (`white-space: nowrap` would work and might be acceptible for a 1px offset, but it will create bad cutoffs for bigger offsets...)

> We are reworking the DOM renderer in https://github.com/xtermjs/xterm.js/pull/4605 and it looks like it still happens there.

Yes thats very likely, as it is just a span merging drop-in atm (everything else is still the same logic).

**Comment by jerch** [comment] 2023-07-29 23:09
This gets fixed in the new DOM PR by the `white-space: pre` css rule there.

**Closed** 2023-08-01 19:32 UTC
Labels: type/bug, browser/firefox, area/renderer-dom
