### ISSUE TITLE
Probably incorrect horizontal cursor positioning with certain CSI sequences

### ISSUE THREAD

**Issue by cubiclesoft** [xtermjs/xterm.js#2020] opened 2019-04-19 14:09 UTC
It appears to be possible to put the `buffer.x` position into an odd state with certain CSI sequences.

### Sample

```
\E[4000G\E[B
```

Or:

```
\E[4000G\E[e
```

### Analysis

```js
    InputHandler.prototype.cursorCharAbsolute = function (params) {
        var param = params[0];
        if (param < 1) {
            param = 1;
        }
        this._terminal.buffer.x = param - 1;
    };

    InputHandler.prototype.cursorDown = function (params) {
        var param = params[0];
        if (param < 1) {
            param = 1;
        }
        this._terminal.buffer.y += param;
        if (this._terminal.buffer.y >= this._terminal.rows) {
            this._terminal.buffer.y = this._terminal.rows - 1;
        }
        if (this._terminal.buffer.x >= this._terminal.cols) {
            this._terminal.buffer.x--;
        }
    };

    InputHandler.prototype.vPositionRelative = function (params) {
        var param = params[0];
        if (param < 1) {
            param = 1;
        }
        this._terminal.buffer.y += param;
        if (this._terminal.buffer.y >= this._terminal.rows) {
            this._terminal.buffer.y = this._terminal.rows - 1;
        }
        if (this._terminal.buffer.x >= this._terminal.cols) {
            this._terminal.buffer.x--;
        }
    };
```

Not quite sure what the purpose of the `x--` is.  If the goal is to always cap it within the max columns, then that won't necessarily work properly here.

On an unrelated note, `cursorDown` and `vPositionRelative` contain identical code.  `cursorForward` and `hPositionRelative` also contain identical code.  Also, `cursorPosition` and `hVPosition` appear to have logically identical code but `hVPosition` is shorter and more readable, IMO.

**Comment by Tyriar** [comment] 2019-04-20 21:16
I think the `x--` is because printing can push the cursor to equal this._terminal.cols and only on the next print will it move to the following line.

**Comment by jerch** [comment] 2019-04-28 10:25
Yep, the `x--` tries to fix the faulty cursor position handling on sequence basis atm, a more general fix is needed as pointed out by #1434.

**Comment by Tyriar** [comment] 2019-04-30 19:21
@jerch is this a dupe of #1434?

**Comment by jerch** [comment] 2019-04-30 19:32
Kinda, its a part of it.

**Comment by Tyriar** [comment] 2019-04-30 19:35
@jerch just the code duplication part is not?

**Comment by jerch** [comment] 2019-04-30 19:52
Well the code duplication part is the try to fix the wrong positioning for certain methods, while others have not this "sanity" check yet. I guess there are more that can show this overflow (not checked), some methods even try to fix it on enter with a precheck (`print` for example always checks this before inserting chars to the buffer).
It happens to work atm with this mixture of post- and postcheck/corrections, still the cursor is sometimes off (`top` shows the cursor wrongly in first column during screen refreshs). #1434 tried to address this but I kinda got distracted from it (and the fix was more an ugly hack).

**Closed** 2019-07-11 22:37 UTC
Labels: area/parser, type/bug
