### ISSUE TITLE
Firefox 50000px Wide `div` Overflow/Scroll

### ISSUE THREAD

**Issue by moloch--** [xtermjs/xterm.js#4810] opened 2023-09-16 18:00 UTC
## Details
- Browser and browser version: Firefox 118
- OS version: MacOS 13.5.2
- xterm.js version: 5.3.0

### Steps to reproduce

Initializing an xtermjs instance in Firefox creates a 50000px wide `div` in the body (see below) that makes the page scroll horizontally for 50000px pixels regardless of the terminal's container.

Chrome does not have the same scrolling behavior.

```
<div style="position: absolute; top: -50000px; width: 50000px; white-space: pre; font-kerning: none; font-family: Fira Code; font-size: 15px;"><span style="font-weight: normal;">$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$</span><span style="font-weight: bold;"></span><span style="font-style: italic; font-weight: normal;"></span><span style="font-weight: bold; font-style: italic;">ssssssssssssssssssssssssssssssss</span></div>
```

**Comment by rijenkii** [comment] 2023-09-18 06:30
Duplicate of #4805?

**Closed** 2023-09-18 15:05 UTC
