### ISSUE TITLE
Import module directly from unpkg

### ISSUE THREAD

**Issue by candlerb** [xtermjs/xterm.js#3083] opened 2020-09-07 16:54 UTC
I believe it should be possible to import ES modules directly from unpkg - [working examples](https://github.com/preactjs/preact/issues/1961#issuecomment-537255092).

However it doesn't appear to work with xterm.js.

Try 1:

```
<script type="module">
import { Terminal } from 'https://unpkg.com/xterm@latest?module';
alert("OK!");
</script>
```

This redirects to `/xterm@4.8.1?module` which returns 404 with message "Package xterm@4.8.1 does not contain an ES module"

Try 2:

```
<script type="module">
import { Terminal } from 'https://unpkg.com/xterm@latest/lib/xterm.js?module';
alert("OK!");
</script>
```

This URL serves some minified Javascript, but the import aborts with:

> Uncaught SyntaxError: The requested module 'https://unpkg.com/xterm@latest/lib/xterm.js?module' does not provide an export named 'Terminal'

Have I missed something, or would something need changing in xterm.js to support this?

**Comment by Tyriar** [comment] 2020-09-07 18:18
Duplicate of https://github.com/xtermjs/xterm.js/issues/2878

**Closed by Tyriar** 2020-09-07 18:18 UTC
