### ISSUE TITLE
Resizing when writing causes text to disappear and spaces to appear

### ISSUE THREAD

**Issue by xReav3r** [xtermjs/xterm.js#4639] opened 2023-08-02 19:33 UTC
If not resizing when writing (now I can resize as I want and text is correct):
![image](https://github.com/xtermjs/xterm.js/assets/47347131/4c6aaeb1-7fe4-4cf8-b461-002b1fcce92b)

If resizing when writing:
![image](https://github.com/xtermjs/xterm.js/assets/47347131/4434e045-5d51-4953-9719-5759cd13ce79)

Tried fitAddon.fit() and even terminal.resize(fitAddon.proposeDimensions()).
Also tried to debounce to 500 ms with no luck.

Data is written by chunks as Uint8Array from ReadableStream.

## Details
- Browser and browser version: Chrome 114.0.5735.133 (Official Build) (64-bit)
- OS version: Linux 5.15.114-2-MANJARO x86_64 GNU/Linux
- xterm.js version: 5.2.1

### Steps to reproduce

1.  Call write periodically.
2.  Call resize.

**Comment by Tyriar** [comment] 2023-08-03 14:02
@xReav3r any more details on how you're writing and what you mean by writing periodically? I can't reproduce this but it would be great to fix it.

**Comment by xReav3r** [comment] 2023-08-05 11:23
Managed to simulate it here (just resize the window width under line width):
https://codesandbox.io/s/kind-http-xkj3jt?file=/src/App.js&resolutionWidth=802&resolutionHeight=675

**Comment by Tyriar** [comment] 2023-08-05 13:27
Do you mean how it goes like this when you make it really narrow?

![image](https://github.com/xtermjs/xterm.js/assets/2193314/1fb3a06e-58f9-4968-9da6-7cee5fb70ebb)

**Comment by xReav3r** [comment] 2023-08-05 14:51
Yes, but it just need to be narrower than line, even if it is one character, but looks like it depends on the text that goes before endline. In real usage I am streaming real terminal trought ReadableStream, where size of chunk is "random".

When resizing over line width everything is okay.

**Comment by ithrforu** [comment] 2023-09-12 05:01
I have a similar bug with resizing. Everything is ok without text, but  if i paste the text it starts to duplicate and look weird:

[xterm5-3-0-zoom.webm](https://github.com/xtermjs/xterm.js/assets/81531000/952c911f-8413-4901-bab6-5a6870bf3910)

```
  useEffect(() => {
    const ws = new WebSocket(
      [
        'wss://',
        window.location.host, // Это путь, по которому открыт Ideco UTM в браузере. Может оканчиваться на /, или нет.
        window.location.pathname.replace(/\/?$/, '/') +
          getBackendReqPrefix('/web-terminal'),
      ].join('')
    );

    const terminal = new Terminal();
    const attachAddon = new AttachAddon(ws);
    const fitAddon = new FitAddon();

    terminal.loadAddon(attachAddon);
    terminal.loadAddon(fitAddon);

    const doCloseOK = () => {
      terminal.dispose();
      setIsClose(true);
    };
    ws.addEventListener('close', doCloseOK);

    const doCloseOnError = () => {
      terminal.dispose();
      setIsError(true);
    };
    ws.addEventListener('error', doCloseOnError);

    const sendResize = (cols: number, rows: number) => {
      ws.readyState === WebSocket.OPEN &&
        ws.send(
          new Blob(
            [
              JSON.stringify({
                type: 'resize',
                cols,
                rows,
              }),
            ],
            { type: 'application/json' }
          )
        );
    };
    const doSendResize = () => sendResize(terminal.cols, terminal.rows);
    ws.addEventListener('open', doSendResize);

    terminal.open(notNull(terminalRef.current));
    terminal.onResize((size) => sendResize(size.cols, size.rows));

    const resizeObserver = new ResizeObserver(() => {
      requestAnimationFrame(() => {
        fitAddon.proposeDimensions();
        fitAddon.fit();
      });
    });

    resizeObserver.observe(notNull(terminalRef.current));

    return () => {
      resizeObserver.disconnect();
      ws.removeEventListener('open', doSendResize);
      ws.removeEventListener('close', doCloseOK);
      ws.removeEventListener('error', doCloseOnError);
      window.removeEventListener('beforeunload', onBeforeUnload);
      terminal.dispose();
      ws.close(1000);
    };
  }, []);
```

**Comment by zk923852367** [comment] 2023-09-13 08:08
I also encountered the same problem. After the browser was scaled, due to the fact that the row height was not an integer when calculating rows, there was an error in the calculation. Finally, when calculating the total height of the container, there was a difference from the actual container height, resulting in some content being occluded

**Comment by ithrforu** [comment] 2023-10-26 13:38
Any updates? Still relevant.

**Comment by Tyriar** [comment] 2024-12-12 16:36
I think this is just related to reflow no working as expected when writing directly to the terminal instead of via a pty. Closing as designed since AFAIK everything works fine when a shell is running (with some known exceptions across most terminals), if you can't reproduce this in the xterm.js demo it's likely not a problem.

Also if reflow around the cursor is an issue a change was just merged in for this: https://github.com/xtermjs/xterm.js/pull/5234

**Closed by Tyriar** 2024-12-12 16:36 UTC
